# Generated by Django 5.2.8 on 2026-09-01 09:25

import apps.assinaturas.subapps.faturamento.payloads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SQL = r"""
ALTER TABLE public.checkout_cobranca ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkout_cobranca FORCE ROW LEVEL SECURITY;
CREATE POLICY isolamento_organizacao ON public.checkout_cobranca
USING (organizacao_id = NULLIF(current_setting('rls.tenant_id', true), '')::integer)
WITH CHECK (organizacao_id = NULLIF(current_setting('rls.tenant_id', true), '')::integer);
ALTER TABLE public.fatura_assinatura ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fatura_assinatura FORCE ROW LEVEL SECURITY;
CREATE POLICY isolamento_organizacao ON public.fatura_assinatura
USING (organizacao_id = NULLIF(current_setting('rls.tenant_id', true), '')::integer)
WITH CHECK (organizacao_id = NULLIF(current_setting('rls.tenant_id', true), '')::integer);
ALTER TABLE public.evento_cobranca ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evento_cobranca FORCE ROW LEVEL SECURITY;
CREATE POLICY evento_tenant ON public.evento_cobranca
USING (organizacao_id = NULLIF(current_setting('rls.tenant_id', true), '')::integer)
WITH CHECK (organizacao_id = NULLIF(current_setting('rls.tenant_id', true), '')::integer);

CREATE FUNCTION public.faturamento_validar_coerencia_organizacao() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog, pg_temp AS $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM public.assinatura_organizacao a WHERE a.id=NEW.assinatura_id AND a.organizacao_id=NEW.organizacao_id) THEN
  RAISE EXCEPTION 'organizacao divergente da assinatura' USING ERRCODE='23514';
 END IF;
 IF TG_TABLE_NAME='checkout_cobranca' THEN
  IF NEW.alteracao_id IS NOT NULL AND NOT EXISTS (
   SELECT 1 FROM public.alteracao_assinatura a WHERE a.id=NEW.alteracao_id AND a.organizacao_id=NEW.organizacao_id AND a.assinatura_id=NEW.assinatura_id
  ) THEN RAISE EXCEPTION 'alteracao divergente do checkout' USING ERRCODE='23514'; END IF;
  IF NEW.proposta_id IS NOT NULL AND NOT EXISTS (
   SELECT 1 FROM public.proposta_comercial p WHERE p.id=NEW.proposta_id AND p.organizacao_id=NEW.organizacao_id AND p.status=30
  ) THEN RAISE EXCEPTION 'proposta divergente ou nao aceita' USING ERRCODE='23514'; END IF;
  IF NEW.finalidade=10 AND NOT EXISTS (
   SELECT 1 FROM public.assinatura_organizacao a WHERE a.id=NEW.assinatura_id AND a.status=10 AND a.proposta_comercial_id IS NULL
  ) THEN RAISE EXCEPTION 'contratacao exige assinatura pendente' USING ERRCODE='23514'; END IF;
  IF NEW.finalidade IN (30,40) AND NOT EXISTS (
   SELECT 1 FROM public.assinatura_organizacao a WHERE a.id=NEW.assinatura_id AND a.status<>40
  ) THEN RAISE EXCEPTION 'checkout exige assinatura corrente' USING ERRCODE='23514'; END IF;
 END IF;
 RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.faturamento_validar_coerencia_organizacao() FROM PUBLIC;
CREATE TRIGGER assinatura_gateway_coerencia BEFORE INSERT OR UPDATE ON public.assinatura_gateway
FOR EACH ROW EXECUTE FUNCTION public.faturamento_validar_coerencia_organizacao();
CREATE TRIGGER checkout_cobranca_coerencia BEFORE INSERT OR UPDATE ON public.checkout_cobranca
FOR EACH ROW EXECUTE FUNCTION public.faturamento_validar_coerencia_organizacao();
CREATE TRIGGER fatura_assinatura_coerencia BEFORE INSERT OR UPDATE ON public.fatura_assinatura
FOR EACH ROW EXECUTE FUNCTION public.faturamento_validar_coerencia_organizacao();

CREATE FUNCTION public.texto_timestamp_valido(text) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT SECURITY INVOKER SET search_path=pg_catalog,pg_temp AS $$
BEGIN
 PERFORM $1::timestamptz;
 RETURN $1 ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]{1,6})?(Z|[+-](0[0-9]|1[0-4]):[0-5][0-9])$';
EXCEPTION WHEN OTHERS THEN RETURN false;
END;
$$;
REVOKE ALL ON FUNCTION public.texto_timestamp_valido(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.texto_timestamp_valido(text) TO PUBLIC;
CREATE FUNCTION public.evento_payload_valido(jsonb) RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT SECURITY INVOKER SET search_path=pg_catalog,pg_temp AS $$
SELECT jsonb_typeof($1)='object'
AND ARRAY(SELECT jsonb_object_keys($1)) <@ ARRAY[
 'amount','currency','customer_reference','failure_code','invoice_status',
 'payment_status','period_end','period_start','subscription_status']::text[]
AND NOT EXISTS (SELECT 1 FROM jsonb_each($1) item WHERE CASE item.key
 WHEN 'amount' THEN jsonb_typeof(item.value)<>'number' OR (item.value#>>'{}')!~'^[0-9]+$' OR (item.value#>>'{}')::numeric>9223372036854775807
 WHEN 'currency' THEN jsonb_typeof(item.value)<>'string' OR (item.value#>>'{}')!~'^[A-Z]{3}$'
 WHEN 'customer_reference' THEN jsonb_typeof(item.value)<>'string' OR (item.value#>>'{}')!~'^[A-Za-z0-9_.:~-]{1,512}$'
 WHEN 'failure_code' THEN jsonb_typeof(item.value)<>'string' OR (item.value#>>'{}')!~'^[A-Za-z0-9_.:-]{1,100}$'
 WHEN 'invoice_status' THEN jsonb_typeof(item.value)<>'string' OR (item.value#>>'{}')!~'^[a-z][a-z0-9_.-]{0,49}$'
 WHEN 'payment_status' THEN jsonb_typeof(item.value)<>'string' OR (item.value#>>'{}')!~'^[a-z][a-z0-9_.-]{0,49}$'
 WHEN 'subscription_status' THEN jsonb_typeof(item.value)<>'string' OR (item.value#>>'{}')!~'^[a-z][a-z0-9_.-]{0,49}$'
 WHEN 'period_start' THEN jsonb_typeof(item.value)<>'string' OR NOT public.texto_timestamp_valido(item.value#>>'{}')
 WHEN 'period_end' THEN jsonb_typeof(item.value)<>'string' OR NOT public.texto_timestamp_valido(item.value#>>'{}')
 ELSE true END);
$$;
REVOKE ALL ON FUNCTION public.evento_payload_valido(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.evento_payload_valido(jsonb) TO PUBLIC;
ALTER TABLE public.evento_cobranca ADD CONSTRAINT evento_payload_schema_seguro CHECK (public.evento_payload_valido(payload_normalizado));

GRANT USAGE ON SCHEMA public TO billing_ingress_runtime;
REVOKE ALL ON public.evento_cobranca, public.assinatura_gateway FROM billing_ingress_runtime;
REVOKE ALL ON SEQUENCE public.evento_cobranca_id_seq FROM billing_ingress_runtime;
GRANT USAGE ON SCHEMA public TO __BILLING_OWNER__;
GRANT SELECT,INSERT,UPDATE ON public.evento_cobranca TO __BILLING_OWNER__;
GRANT SELECT ON public.assinatura_gateway TO __BILLING_OWNER__;
GRANT USAGE,SELECT ON SEQUENCE public.evento_cobranca_id_seq TO __BILLING_OWNER__;
CREATE POLICY evento_interface_definidor_select ON public.evento_cobranca FOR SELECT TO __BILLING_OWNER__ USING (true);
CREATE POLICY evento_interface_definidor_insert ON public.evento_cobranca FOR INSERT TO __BILLING_OWNER__ WITH CHECK (true);
CREATE POLICY evento_interface_definidor_update ON public.evento_cobranca FOR UPDATE TO __BILLING_OWNER__ USING (true) WITH CHECK (true);

CREATE FUNCTION public.faturamento_receber_evento(text,text,text,text,text,text,boolean,jsonb,text,timestamptz)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE inseridas integer;
BEGIN
 IF NULLIF(current_setting('role',true),'') IS DISTINCT FROM 'billing_ingress_runtime'
 OR NULLIF(current_setting('rls.tenant_id',true),'')::integer IS DISTINCT FROM 0
 OR NULLIF(current_setting('rls.billing_ingress',true),'') IS DISTINCT FROM '1' THEN
  RAISE EXCEPTION 'papel e contexto de ingresso obrigatorios' USING ERRCODE='42501'; END IF;
 IF $1 IS NULL OR length($1) NOT BETWEEN 1 AND 50 OR $2 IS NULL OR length($2) NOT BETWEEN 1 AND 255
 OR $3 IS NULL OR length($3) NOT BETWEEN 1 AND 100 OR $3!~'^[a-z][a-z0-9]*([._][a-z0-9]+)*$' OR $3~'[^a-z0-9._]'
 OR length(COALESCE($4,''))>255 OR length(COALESCE($5,''))>255 OR length(COALESCE($6,''))>255 OR $7 IS NULL
 OR $8 IS NULL OR NOT public.evento_payload_valido($8) OR $9 IS NULL OR $9!~'^[0-9a-f]{64}$' THEN
  RAISE EXCEPTION 'evento normalizado invalido' USING ERRCODE='22023'; END IF;
 INSERT INTO public.evento_cobranca(created_at,last_modified_at,is_active,is_deleted,variante,identificador_evento,tipo,
 identificador_assinatura,identificador_checkout,identificador_fatura,status,exige_tenant,tentativas_roteamento,
 tentativas_processamento,payload_normalizado,hash_payload,erro,ocorrido_em)
 VALUES(statement_timestamp(),statement_timestamp(),true,false,$1,$2,$3,COALESCE($4,''),COALESCE($5,''),COALESCE($6,''),10,$7,0,0,$8,$9,'',$10)
 ON CONFLICT(variante,identificador_evento) DO NOTHING;
 GET DIAGNOSTICS inseridas=ROW_COUNT; RETURN inseridas=1;
END;
$$;
REVOKE ALL ON FUNCTION public.faturamento_receber_evento(text,text,text,text,text,text,boolean,jsonb,text,timestamptz) FROM PUBLIC;
ALTER FUNCTION public.faturamento_receber_evento(text,text,text,text,text,text,boolean,jsonb,text,timestamptz) OWNER TO __BILLING_OWNER__;
GRANT EXECUTE ON FUNCTION public.faturamento_receber_evento(text,text,text,text,text,text,boolean,jsonb,text,timestamptz) TO billing_ingress_runtime;
CREATE FUNCTION public.faturamento_rotear_evento(text,text) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE alteradas integer;
BEGIN
 IF NULLIF(current_setting('role',true),'') IS DISTINCT FROM 'billing_ingress_runtime'
 OR NULLIF(current_setting('rls.tenant_id',true),'')::integer IS DISTINCT FROM 0
 OR NULLIF(current_setting('rls.billing_ingress',true),'') IS DISTINCT FROM '1' THEN
  RAISE EXCEPTION 'papel e contexto de ingresso obrigatorios' USING ERRCODE='42501'; END IF;
 UPDATE public.evento_cobranca e SET organizacao_id=g.organizacao_id,status=20,last_modified_at=statement_timestamp()
 FROM public.assinatura_gateway g WHERE e.variante=$1 AND e.identificador_evento=$2 AND e.organizacao_id IS NULL
 AND g.variante=e.variante AND g.identificador_externo=e.identificador_assinatura AND g.is_active AND NOT g.is_deleted;
 GET DIAGNOSTICS alteradas=ROW_COUNT; RETURN alteradas=1;
END;
$$;
REVOKE ALL ON FUNCTION public.faturamento_rotear_evento(text,text) FROM PUBLIC;
ALTER FUNCTION public.faturamento_rotear_evento(text,text) OWNER TO __BILLING_OWNER__;
GRANT EXECUTE ON FUNCTION public.faturamento_rotear_evento(text,text) TO billing_ingress_runtime;
"""

REVERSE_SQL = r"""
REVOKE ALL ON FUNCTION public.faturamento_rotear_evento(text,text) FROM billing_ingress_runtime;
REVOKE ALL ON FUNCTION public.faturamento_receber_evento(text,text,text,text,text,text,boolean,jsonb,text,timestamptz) FROM billing_ingress_runtime;
DROP FUNCTION public.faturamento_rotear_evento(text,text);
DROP FUNCTION public.faturamento_receber_evento(text,text,text,text,text,text,boolean,jsonb,text,timestamptz);
DROP TRIGGER fatura_assinatura_coerencia ON public.fatura_assinatura;
DROP TRIGGER checkout_cobranca_coerencia ON public.checkout_cobranca;
DROP TRIGGER assinatura_gateway_coerencia ON public.assinatura_gateway;
DROP FUNCTION public.faturamento_validar_coerencia_organizacao();
DROP FUNCTION public.evento_payload_valido(jsonb) CASCADE;
DROP FUNCTION public.texto_timestamp_valido(text);
REVOKE ALL ON public.evento_cobranca,public.assinatura_gateway FROM __BILLING_OWNER__;
REVOKE ALL ON SEQUENCE public.evento_cobranca_id_seq FROM __BILLING_OWNER__;
REVOKE USAGE ON SCHEMA public FROM __BILLING_OWNER__;
REVOKE USAGE ON SCHEMA public FROM billing_ingress_runtime;
"""


def preflight(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    owner = settings.BILLING_DATABASE_OWNER_ROLE
    runtime = settings.BILLING_INGRESS_DATABASE_ROLE
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """SELECT rolname,rolcanlogin,rolsuper,rolbypassrls,rolcreaterole,rolcreatedb,rolinherit,rolreplication,
                      pg_has_role(current_user,oid,'SET'), EXISTS(SELECT 1 FROM pg_auth_members WHERE member=pg_roles.oid)
               FROM pg_roles WHERE rolname IN (%s,%s) ORDER BY rolname""",
            [owner, runtime],
        )
        roles = cursor.fetchall()
    if owner == runtime or len(roles) != 2 or any(row[1:8] != (False, False, False, False, False, False, False) or row[9] for row in roles):
        raise RuntimeError("As roles de faturamento não existem ou possuem atributos/memberships inseguros.")
    memberships = {row[0]: row[8] for row in roles}
    if not memberships[owner]:
        raise RuntimeError("A credencial DDL deve poder executar SET ROLE para o owner de faturamento.")


def instalar(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        owner = schema_editor.connection.ops.quote_name(settings.BILLING_DATABASE_OWNER_ROLE)
        schema_editor.execute(SQL.replace("__BILLING_OWNER__", owner))


def remover(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        owner = schema_editor.connection.ops.quote_name(settings.BILLING_DATABASE_OWNER_ROLE)
        schema_editor.execute(REVERSE_SQL.replace("__BILLING_OWNER__", owner))


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinaturas', '0013_proteger_revisao_e_upserts'),
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AssinaturaGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50)),
                ('identificador_externo', models.CharField(max_length=255)),
                ('assinatura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gateway', to='assinaturas.assinaturaorganizacao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_gateway', to='organizacoes.organizacao')),
            ],
            options={
                'db_table': 'assinatura_gateway',
                'constraints': [models.UniqueConstraint(fields=('variante', 'identificador_externo'), name='assinatura_gateway_id_externo_global')],
            },
        ),
        migrations.CreateModel(
            name='CheckoutCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('finalidade', models.PositiveSmallIntegerField(choices=[(10, 'Contratação'), (20, 'Alteração'), (30, 'Proposta'), (40, 'Forma de pagamento')])),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Criado'), (20, 'Aguardando gateway'), (30, 'Aberto'), (40, 'Concluído'), (50, 'Expirado'), (60, 'Cancelado'), (70, 'Falhou')], default=10)),
                ('chave_idempotencia', models.CharField(max_length=120)),
                ('variante', models.CharField(max_length=50)),
                ('identificador_externo', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('valor_esperado_centavos', models.PositiveBigIntegerField()),
                ('moeda_esperada', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Informe três letras maiúsculas.', regex='^[A-Z]{3}$')])),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_cobranca', to='assinaturas.alteracaoassinatura')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_cobranca', to='assinaturas.assinaturaorganizacao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização')),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_cobranca', to='assinaturas.propostacomercial')),
            ],
            options={
                'db_table': 'checkout_cobranca',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organizacao', 'chave_idempotencia'), name='checkout_chave_unica_por_org'), models.UniqueConstraint(condition=models.Q(('identificador_externo__isnull', False)), fields=('variante', 'identificador_externo'), name='checkout_id_externo_global'), models.CheckConstraint(condition=models.Q(('moeda_esperada__regex', '^[A-Z]{3}$')), name='checkout_moeda_iso'), models.CheckConstraint(condition=models.Q(models.Q(('alteracao__isnull', False), ('finalidade', 20), ('proposta__isnull', True)), models.Q(('alteracao__isnull', True), ('finalidade', 30), ('proposta__isnull', False)), models.Q(('alteracao__isnull', True), ('finalidade__in', (10, 40)), ('proposta__isnull', True)), _connector='OR'), name='checkout_finalidade_referencias'), models.CheckConstraint(condition=models.Q(models.Q(('finalidade', 40), _negated=True), ('valor_esperado_centavos', 0), _connector='OR'), name='checkout_forma_pagamento_zero')],
            },
        ),
        migrations.CreateModel(
            name='EventoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50)),
                ('identificador_evento', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100, validators=[apps.assinaturas.subapps.faturamento.payloads.validar_tipo_evento])),
                ('identificador_assinatura', models.CharField(blank=True, max_length=255)),
                ('identificador_checkout', models.CharField(blank=True, max_length=255)),
                ('identificador_fatura', models.CharField(blank=True, max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Recebido'), (20, 'Roteado'), (30, 'Processando'), (40, 'Processado'), (50, 'Ignorado'), (60, 'Falhou')], default=10)),
                ('exige_tenant', models.BooleanField(default=True)),
                ('tentativas_roteamento', models.PositiveSmallIntegerField(default=0)),
                ('tentativas_processamento', models.PositiveSmallIntegerField(default=0)),
                ('payload_normalizado', models.JSONField(default=dict, validators=[apps.assinaturas.subapps.faturamento.payloads.validar_payload_evento])),
                ('hash_payload', models.CharField(max_length=64)),
                ('erro', models.CharField(blank=True, max_length=500)),
                ('ocorrido_em', models.DateTimeField(blank=True, null=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_cobranca', to='organizacoes.organizacao')),
            ],
            options={
                'db_table': 'evento_cobranca',
                'constraints': [models.UniqueConstraint(fields=('variante', 'identificador_evento'), name='evento_cobranca_id_global'), models.CheckConstraint(condition=models.Q(models.Q(('exige_tenant', True), ('status', 40), _negated=True), ('organizacao__isnull', False), _connector='OR'), name='evento_processado_exige_tenant'), models.CheckConstraint(condition=models.Q(('tipo__regex', '^[a-z][a-z0-9]*([._][a-z0-9]+)*$'), models.Q(('tipo__regex', '[^a-z0-9._]'), _negated=True)), name='evento_tipo_normalizado')],
            },
        ),
        migrations.CreateModel(
            name='FaturaAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50)),
                ('identificador_externo', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Aberta'), (20, 'Paga'), (30, 'Vencida'), (40, 'Irrecuperável'), (50, 'Anulada')])),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('subtotal_centavos', models.PositiveBigIntegerField(default=0)),
                ('desconto_centavos', models.PositiveBigIntegerField(default=0)),
                ('imposto_centavos', models.PositiveBigIntegerField(default=0)),
                ('total_centavos', models.PositiveBigIntegerField(default=0)),
                ('moeda', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Informe três letras maiúsculas.', regex='^[A-Z]{3}$')])),
                ('periodo_iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('periodo_termina_em', models.DateTimeField(blank=True, null=True)),
                ('vencimento_em', models.DateTimeField(blank=True, null=True)),
                ('paga_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('url_hospedada', models.URLField(blank=True, max_length=2048)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='assinaturas.assinaturaorganizacao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização')),
            ],
            options={
                'db_table': 'fatura_assinatura',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organizacao', 'variante', 'identificador_externo'), name='fatura_id_externo_unico_por_org'), models.CheckConstraint(condition=models.Q(('moeda__regex', '^[A-Z]{3}$')), name='fatura_moeda_iso')],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaPrecoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50)),
                ('componente', models.PositiveSmallIntegerField(choices=[(10, 'Base'), (20, 'Seat')])),
                ('identificador_externo', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('preco_plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_gateway', to='assinaturas.precoplano')),
            ],
            options={
                'db_table': 'referencia_preco_gateway',
                'constraints': [models.UniqueConstraint(fields=('variante', 'identificador_externo'), name='referencia_preco_id_externo_global'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('preco_plano', 'variante', 'componente'), name='referencia_preco_ativa_unica')],
            },
        ),
        migrations.RunPython(instalar, remover),
    ]
