# Generated by Django 5.2.8 on 2026-09-01 06:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class PostgresRunSQL(migrations.RunSQL):
    """Ignora a operação nas bases auxiliares SQLite da suíte."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinaturas', '0013_proteger_revisao_e_upserts'),
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50)),
                ('identificador_externo', models.CharField(max_length=255)),
                ('assinatura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gateway', to='assinaturas.assinaturaorganizacao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_gateway', to='organizacoes.organizacao')),
            ],
            options={
                'db_table': 'assinatura_gateway',
                'constraints': [models.UniqueConstraint(fields=('variante', 'identificador_externo'), name='assinatura_gateway_id_externo_global')],
            },
        ),
        migrations.CreateModel(
            name='CheckoutCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('finalidade', models.PositiveSmallIntegerField(choices=[(10, 'Contratação'), (20, 'Alteração'), (30, 'Proposta'), (40, 'Forma de pagamento')])),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Criado'), (20, 'Aguardando gateway'), (30, 'Aberto'), (40, 'Concluído'), (50, 'Expirado'), (60, 'Cancelado'), (70, 'Falhou')], default=10)),
                ('chave_idempotencia', models.CharField(max_length=120)),
                ('variante', models.CharField(max_length=50)),
                ('identificador_externo', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('valor_esperado_centavos', models.PositiveBigIntegerField()),
                ('moeda_esperada', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Informe três letras maiúsculas.', regex='^[A-Z]{3}$')])),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_cobranca', to='assinaturas.alteracaoassinatura')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_cobranca', to='assinaturas.assinaturaorganizacao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização')),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_cobranca', to='assinaturas.propostacomercial')),
            ],
            options={
                'db_table': 'checkout_cobranca',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organizacao', 'chave_idempotencia'), name='checkout_chave_unica_por_org'), models.UniqueConstraint(condition=models.Q(('identificador_externo__isnull', False)), fields=('variante', 'identificador_externo'), name='checkout_id_externo_global'), models.CheckConstraint(condition=models.Q(('moeda_esperada__regex', '^[A-Z]{3}$')), name='checkout_moeda_iso'), models.CheckConstraint(condition=models.Q(models.Q(('alteracao__isnull', False), ('finalidade', 20), ('proposta__isnull', True)), models.Q(('alteracao__isnull', True), ('finalidade', 30), ('proposta__isnull', False)), models.Q(('alteracao__isnull', True), ('finalidade__in', (10, 40)), ('proposta__isnull', True)), _connector='OR'), name='checkout_finalidade_referencias'), models.CheckConstraint(condition=models.Q(models.Q(('finalidade', 40), _negated=True), ('valor_esperado_centavos', 0), _connector='OR'), name='checkout_forma_pagamento_zero')],
            },
        ),
        migrations.CreateModel(
            name='EventoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50)),
                ('identificador_evento', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('identificador_assinatura', models.CharField(blank=True, max_length=255)),
                ('identificador_checkout', models.CharField(blank=True, max_length=255)),
                ('identificador_fatura', models.CharField(blank=True, max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Recebido'), (20, 'Roteado'), (30, 'Processando'), (40, 'Processado'), (50, 'Ignorado'), (60, 'Falhou')], default=10)),
                ('exige_tenant', models.BooleanField(default=True)),
                ('tentativas_roteamento', models.PositiveSmallIntegerField(default=0)),
                ('tentativas_processamento', models.PositiveSmallIntegerField(default=0)),
                ('payload_normalizado', models.JSONField(default=dict)),
                ('hash_payload', models.CharField(max_length=64)),
                ('erro', models.CharField(blank=True, max_length=500)),
                ('ocorrido_em', models.DateTimeField(blank=True, null=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_cobranca', to='organizacoes.organizacao')),
            ],
            options={
                'db_table': 'evento_cobranca',
                'constraints': [models.UniqueConstraint(fields=('variante', 'identificador_evento'), name='evento_cobranca_id_global'), models.CheckConstraint(condition=models.Q(models.Q(('exige_tenant', True), ('status', 40), _negated=True), ('organizacao__isnull', False), _connector='OR'), name='evento_processado_exige_tenant')],
            },
        ),
        migrations.CreateModel(
            name='FaturaAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50)),
                ('identificador_externo', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Aberta'), (20, 'Paga'), (30, 'Vencida'), (40, 'Irrecuperável'), (50, 'Anulada')])),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('subtotal_centavos', models.PositiveBigIntegerField(default=0)),
                ('desconto_centavos', models.PositiveBigIntegerField(default=0)),
                ('imposto_centavos', models.PositiveBigIntegerField(default=0)),
                ('total_centavos', models.PositiveBigIntegerField(default=0)),
                ('moeda', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Informe três letras maiúsculas.', regex='^[A-Z]{3}$')])),
                ('periodo_iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('periodo_termina_em', models.DateTimeField(blank=True, null=True)),
                ('vencimento_em', models.DateTimeField(blank=True, null=True)),
                ('paga_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('url_hospedada', models.URLField(blank=True, max_length=2048)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='assinaturas.assinaturaorganizacao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização')),
            ],
            options={
                'db_table': 'fatura_assinatura',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organizacao', 'variante', 'identificador_externo'), name='fatura_id_externo_unico_por_org'), models.CheckConstraint(condition=models.Q(('moeda__regex', '^[A-Z]{3}$')), name='fatura_moeda_iso')],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaPrecoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50)),
                ('componente', models.PositiveSmallIntegerField(choices=[(10, 'Base'), (20, 'Seat')])),
                ('identificador_externo', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('preco_plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_gateway', to='assinaturas.precoplano')),
            ],
            options={
                'db_table': 'referencia_preco_gateway',
                'constraints': [models.UniqueConstraint(fields=('variante', 'identificador_externo'), name='referencia_preco_id_externo_global'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('preco_plano', 'variante', 'componente'), name='referencia_preco_ativa_unica')],
            },
        ),
        PostgresRunSQL(
            sql='''
                ALTER TABLE "checkout_cobranca" ENABLE ROW LEVEL SECURITY;
                ALTER TABLE "checkout_cobranca" FORCE ROW LEVEL SECURITY;
                CREATE POLICY isolamento_organizacao ON checkout_cobranca USING (organizacao_id = (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer)) WITH CHECK (organizacao_id = (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer));
                ALTER TABLE "fatura_assinatura" ENABLE ROW LEVEL SECURITY;
                ALTER TABLE "fatura_assinatura" FORCE ROW LEVEL SECURITY;
                CREATE POLICY isolamento_organizacao ON fatura_assinatura USING (organizacao_id = (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer)) WITH CHECK (organizacao_id = (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer));
                ALTER TABLE "evento_cobranca" ENABLE ROW LEVEL SECURITY;
                ALTER TABLE "evento_cobranca" FORCE ROW LEVEL SECURITY;
                CREATE POLICY evento_tenant ON evento_cobranca USING (organizacao_id = (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer)) WITH CHECK (organizacao_id = (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer));
                CREATE POLICY evento_ingresso_select ON evento_cobranca FOR SELECT USING (organizacao_id IS NULL AND (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer) = 0 AND (SELECT NULLIF(current_setting('rls.billing_ingress', true), '')) = '1');
                CREATE POLICY evento_ingresso_insert ON evento_cobranca FOR INSERT WITH CHECK (organizacao_id IS NULL AND (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer) = 0 AND (SELECT NULLIF(current_setting('rls.billing_ingress', true), '')) = '1');
                CREATE POLICY evento_ingresso_update ON evento_cobranca FOR UPDATE USING (organizacao_id IS NULL AND (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer) = 0 AND (SELECT NULLIF(current_setting('rls.billing_ingress', true), '')) = '1') WITH CHECK (organizacao_id IS NOT NULL AND (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer) = 0 AND (SELECT NULLIF(current_setting('rls.billing_ingress', true), '')) = '1');

                CREATE FUNCTION faturamento_validar_coerencia_organizacao()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    IF TG_TABLE_NAME = 'assinatura_gateway' THEN
                        IF NOT EXISTS (SELECT 1 FROM assinatura_organizacao a WHERE a.id = NEW.assinatura_id AND a.organizacao_id = NEW.organizacao_id) THEN
                            RAISE EXCEPTION 'organizacao divergente da assinatura' USING ERRCODE = '23514';
                        END IF;
                    ELSIF TG_TABLE_NAME = 'fatura_assinatura' THEN
                        IF NOT EXISTS (SELECT 1 FROM assinatura_organizacao a WHERE a.id = NEW.assinatura_id AND a.organizacao_id = NEW.organizacao_id) THEN
                            RAISE EXCEPTION 'organizacao divergente da assinatura' USING ERRCODE = '23514';
                        END IF;
                    ELSE
                        IF NOT EXISTS (SELECT 1 FROM assinatura_organizacao a WHERE a.id = NEW.assinatura_id AND a.organizacao_id = NEW.organizacao_id) THEN
                            RAISE EXCEPTION 'organizacao divergente da assinatura' USING ERRCODE = '23514';
                        END IF;
                        IF NEW.alteracao_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM alteracao_assinatura a WHERE a.id = NEW.alteracao_id AND a.organizacao_id = NEW.organizacao_id AND a.assinatura_id = NEW.assinatura_id) THEN
                            RAISE EXCEPTION 'alteracao divergente do checkout' USING ERRCODE = '23514';
                        END IF;
                        IF NEW.proposta_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM proposta_comercial p WHERE p.id = NEW.proposta_id AND p.organizacao_id = NEW.organizacao_id AND p.status = 30) THEN
                            RAISE EXCEPTION 'proposta divergente ou nao aceita' USING ERRCODE = '23514';
                        END IF;
                        IF NEW.finalidade = 10 AND NOT EXISTS (SELECT 1 FROM assinatura_organizacao a WHERE a.id = NEW.assinatura_id AND a.status = 10 AND a.proposta_comercial_id IS NULL) THEN
                            RAISE EXCEPTION 'contratacao exige assinatura pendente' USING ERRCODE = '23514';
                        END IF;
                        IF NEW.finalidade IN (30, 40) AND NOT EXISTS (SELECT 1 FROM assinatura_organizacao a WHERE a.id = NEW.assinatura_id AND a.status <> 40) THEN
                            RAISE EXCEPTION 'checkout exige assinatura corrente' USING ERRCODE = '23514';
                        END IF;
                    END IF;
                    RETURN NEW;
                END;
                $$;
                CREATE TRIGGER assinatura_gateway_coerencia BEFORE INSERT OR UPDATE ON assinatura_gateway FOR EACH ROW EXECUTE FUNCTION faturamento_validar_coerencia_organizacao();
                CREATE TRIGGER checkout_cobranca_coerencia BEFORE INSERT OR UPDATE ON checkout_cobranca FOR EACH ROW EXECUTE FUNCTION faturamento_validar_coerencia_organizacao();
                CREATE TRIGGER fatura_assinatura_coerencia BEFORE INSERT OR UPDATE ON fatura_assinatura FOR EACH ROW EXECUTE FUNCTION faturamento_validar_coerencia_organizacao();

                CREATE FUNCTION faturamento_rotear_evento(bigint, bigint)
                RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER
                SET search_path = public, pg_temp AS $$
                DECLARE alteradas integer;
                BEGIN
                    IF NULLIF(current_setting('rls.tenant_id', true), '')::integer <> 0
                       OR NULLIF(current_setting('rls.billing_ingress', true), '') <> '1' THEN
                        RAISE EXCEPTION 'contexto de ingresso obrigatorio' USING ERRCODE = '42501';
                    END IF;
                    UPDATE evento_cobranca SET organizacao_id = $2, status = 20, last_modified_at = NOW()
                    WHERE id = $1 AND organizacao_id IS NULL;
                    GET DIAGNOSTICS alteradas = ROW_COUNT;
                    RETURN alteradas = 1;
                END;
                $$;
            ''',
            reverse_sql='''
                DROP FUNCTION IF EXISTS faturamento_rotear_evento(bigint, bigint);
                DROP TRIGGER IF EXISTS fatura_assinatura_coerencia ON fatura_assinatura;
                DROP TRIGGER IF EXISTS checkout_cobranca_coerencia ON checkout_cobranca;
                DROP TRIGGER IF EXISTS assinatura_gateway_coerencia ON assinatura_gateway;
                DROP FUNCTION IF EXISTS faturamento_validar_coerencia_organizacao();
                DROP POLICY IF EXISTS evento_ingresso_update ON evento_cobranca;
                DROP POLICY IF EXISTS evento_ingresso_insert ON evento_cobranca;
                DROP POLICY IF EXISTS evento_ingresso_select ON evento_cobranca;
                DROP POLICY IF EXISTS evento_tenant ON evento_cobranca;
                ALTER TABLE "evento_cobranca" DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS isolamento_organizacao ON fatura_assinatura;
                ALTER TABLE "fatura_assinatura" DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS isolamento_organizacao ON checkout_cobranca;
                ALTER TABLE "checkout_cobranca" DISABLE ROW LEVEL SECURITY;
                ALTER TABLE "evento_cobranca" NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE "fatura_assinatura" NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE "checkout_cobranca" NO FORCE ROW LEVEL SECURITY;
            ''',
        ),
    ]
