# Generated by Django 5.2.8 on 2026-09-01 06:32

import apps.assinaturas.subapps.faturamento.payloads
from django.db import migrations, models


SQL = """
ALTER FUNCTION faturamento_rotear_evento(bigint, bigint) OWNER TO CURRENT_USER;
REVOKE ALL ON FUNCTION faturamento_rotear_evento(bigint, bigint) FROM PUBLIC;
CREATE OR REPLACE FUNCTION faturamento_rotear_evento(bigint, bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp AS $$
DECLARE alteradas integer;
BEGIN
    IF NULLIF(current_setting('rls.tenant_id', true), '')::integer IS DISTINCT FROM 0
       OR NULLIF(current_setting('rls.billing_ingress', true), '') IS DISTINCT FROM '1' THEN
        RAISE EXCEPTION 'contexto de ingresso obrigatorio' USING ERRCODE = '42501';
    END IF;
    UPDATE evento_cobranca SET organizacao_id = $2, status = 20, last_modified_at = NOW()
    WHERE id = $1 AND organizacao_id IS NULL;
    GET DIAGNOSTICS alteradas = ROW_COUNT;
    RETURN alteradas = 1;
END;
$$;
CREATE FUNCTION evento_payload_valido(jsonb) RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT AS $$
    SELECT jsonb_typeof($1) = 'object'
    AND ARRAY(SELECT jsonb_object_keys($1)) <@ ARRAY[
        'amount', 'currency', 'customer_reference', 'failure_code',
        'invoice_status', 'payment_status', 'period_end', 'period_start',
        'subscription_status'
    ]::text[]
    AND NOT EXISTS (
        SELECT 1 FROM jsonb_each($1) item
        WHERE jsonb_typeof(item.value) NOT IN ('string', 'number', 'boolean', 'null')
    );
$$;
ALTER TABLE evento_cobranca ADD CONSTRAINT evento_payload_schema_seguro CHECK (evento_payload_valido(payload_normalizado));
"""

REVERSE_SQL = """
ALTER TABLE evento_cobranca DROP CONSTRAINT IF EXISTS evento_payload_schema_seguro;
DROP FUNCTION IF EXISTS evento_payload_valido(jsonb);
GRANT EXECUTE ON FUNCTION faturamento_rotear_evento(bigint, bigint) TO PUBLIC;
"""


def endurecer_eventos(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(SQL)


def reverter_eventos(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocobranca',
            name='payload_normalizado',
            field=models.JSONField(default=dict, validators=[apps.assinaturas.subapps.faturamento.payloads.validar_payload_evento]),
        ),
        migrations.RunPython(endurecer_eventos, reverter_eventos),
    ]
