# Generated by Django 5.2.8 on 2026-09-02 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_ingestao_eventos'),
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointReconciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50, unique=True)),
                ('janela_inicio', models.DateTimeField()),
                ('janela_fim', models.DateTimeField()),
                ('cursor', models.CharField(blank=True, max_length=500)),
                ('ultimo_limite_concluido', models.DateTimeField(blank=True, null=True)),
                ('lease_ate', models.DateTimeField(blank=True, null=True)),
                ('revisao', models.PositiveBigIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'db_table': 'checkpoint_reconciliacao_cobranca',
                'constraints': [models.CheckConstraint(condition=models.Q(('janela_inicio__lt', models.F('janela_fim'))), name='reconciliacao_janela_valida'), models.CheckConstraint(condition=models.Q(('revisao__gte', 1)), name='reconciliacao_revisao_positiva')],
            },
        ),
        migrations.CreateModel(
            name='ReaberturaEventoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('motivo', models.CharField(max_length=500)),
                ('chave_idempotencia', models.CharField(max_length=120)),
                ('tentativas_anteriores', models.PositiveSmallIntegerField()),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reaberturas_eventos_cobranca', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reaberturas', to='faturamento.eventocobranca')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização')),
            ],
            options={
                'db_table': 'reabertura_evento_cobranca',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organizacao', 'chave_idempotencia'), name='reabertura_evento_chave_org_unica')],
            },
        ),
    ]
