# Generated by Django 5.2.8 on 2026-09-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_reconciliacao_e_retries_operacionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocobranca',
            name='tentativas_automaticas_ciclo',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
    ]
