# Generated by Django 5.2.8 on 2026-09-02 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SQL = """
ALTER TABLE public.solicitacao_reconciliacao_cobranca ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitacao_reconciliacao_cobranca FORCE ROW LEVEL SECURITY;
CREATE POLICY isolamento_organizacao ON public.solicitacao_reconciliacao_cobranca
USING (organizacao_id = NULLIF(current_setting('rls.tenant_id', true), '')::integer)
WITH CHECK (organizacao_id = NULLIF(current_setting('rls.tenant_id', true), '')::integer);
"""
REVERSE_SQL = """
DROP POLICY IF EXISTS isolamento_organizacao ON public.solicitacao_reconciliacao_cobranca;
ALTER TABLE public.solicitacao_reconciliacao_cobranca NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.solicitacao_reconciliacao_cobranca DISABLE ROW LEVEL SECURITY;
"""


def instalar(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(SQL)


def remover(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0009_reconcile_first_conclusivo'),
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoReconciliacaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('variante', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=500)),
                ('chave_idempotencia', models.CharField(max_length=160)),
                ('janela_inicio', models.DateTimeField()),
                ('janela_fim', models.DateTimeField()),
                ('parametros', models.JSONField(default=dict)),
                ('resultado', models.CharField(default='agendada', max_length=30)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliacoes_cobranca_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização')),
            ],
            options={
                'db_table': 'solicitacao_reconciliacao_cobranca',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organizacao', 'chave_idempotencia'), name='solicitacao_reconcile_chave_org_unica'), models.CheckConstraint(condition=models.Q(('janela_inicio__lt', models.F('janela_fim'))), name='solicitacao_reconcile_janela_valida')],
            },
        ),
        migrations.RunPython(instalar, remover),
    ]
