# Generated by Django 5.2.8 on 2026-09-03 14:24

from django.conf import settings
from django.db import migrations, models


SQL = r"""
CREATE OR REPLACE FUNCTION public.faturamento_claim_recovery(integer,timestamptz)
RETURNS TABLE(evento_id bigint,variante varchar(50),organizacao_id bigint)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE item record; destinos bigint[]; destino bigint; retornados integer := 0;
BEGIN
 IF NULLIF(current_setting('role',true),'') IS DISTINCT FROM 'billing_ingress_runtime'
 OR NULLIF(current_setting('rls.tenant_id',true),'')::integer IS DISTINCT FROM 0
 OR NULLIF(current_setting('rls.billing_ingress',true),'') IS DISTINCT FROM '1' THEN
  RAISE EXCEPTION 'papel e contexto operacionais obrigatorios' USING ERRCODE='42501'; END IF;
 IF $1 IS NULL OR $1 NOT BETWEEN 1 AND 1000 OR $2 IS NULL THEN
  RAISE EXCEPTION 'parametros de recovery invalidos' USING ERRCODE='22023'; END IF;
 FOR item IN
   SELECT e.id,e.variante,e.organizacao_id,e.identificador_assinatura,e.identificador_checkout,e.status,e.tentativas_roteamento
   FROM public.evento_cobranca e
   WHERE e.status IN (10,20,30) AND (e.proxima_tentativa_em IS NULL OR e.proxima_tentativa_em <= $2)
     AND (e.recuperacao_arrendada_ate IS NULL OR e.recuperacao_arrendada_ate <= $2)
     AND (e.organizacao_id IS NOT NULL OR e.tentativas_roteamento < 8)
   ORDER BY COALESCE(e.proxima_tentativa_em,e.ocorrido_em),e.id
   FOR UPDATE SKIP LOCKED
 LOOP
   destino := item.organizacao_id;
   IF destino IS NULL THEN
     SELECT array_agg(DISTINCT d.organizacao_id) INTO destinos FROM (
       SELECT g.organizacao_id FROM public.assinatura_gateway g
       WHERE g.variante=item.variante AND g.identificador_externo=item.identificador_assinatura AND g.is_active AND NOT g.is_deleted
       UNION ALL
       SELECT c.organizacao_id FROM public.checkout_cobranca c
       WHERE c.variante=item.variante AND c.identificador_externo=item.identificador_checkout AND c.is_active AND NOT c.is_deleted
     ) d;
     IF cardinality(destinos)=1 THEN destino:=destinos[1]; END IF;
     UPDATE public.evento_cobranca SET tentativas_roteamento=tentativas_roteamento+1,
       organizacao_id=destino,
       status=CASE WHEN destino IS NULL AND item.tentativas_roteamento + 1 >= 8 THEN 60 WHEN destino IS NULL THEN 10 ELSE 20 END,
       proxima_tentativa_em=CASE
         WHEN destino IS NULL AND item.tentativas_roteamento + 1 >= 8 THEN NULL
         WHEN destino IS NULL THEN $2 + make_interval(secs => LEAST(30 * (2 ^ item.tentativas_roteamento)::integer,3600))
         ELSE $2 END,
       erro=CASE WHEN destino IS NULL AND item.tentativas_roteamento + 1 >= 8 THEN 'routing_exhausted' ELSE '' END,
       last_modified_at=statement_timestamp()
     WHERE id=item.id;
   END IF;
   IF destino IS NOT NULL THEN
     UPDATE public.evento_cobranca SET recuperacao_arrendada_ate=$2 + interval '15 minutes' WHERE id=item.id;
     evento_id:=item.id; variante:=item.variante; organizacao_id:=destino; RETURN NEXT;
     retornados := retornados + 1;
     IF retornados >= $1 THEN RETURN; END IF;
   END IF;
 END LOOP;
END;
$$;
REVOKE ALL ON FUNCTION public.faturamento_claim_recovery(integer,timestamptz) FROM PUBLIC;
ALTER FUNCTION public.faturamento_claim_recovery(integer,timestamptz) OWNER TO __BILLING_OWNER__;
GRANT EXECUTE ON FUNCTION public.faturamento_claim_recovery(integer,timestamptz) TO billing_ingress_runtime;
"""


def _owner_financeiro() -> str:
    owner = settings.BILLING_DATABASE_OWNER_ROLE
    if owner != "billing_functions_owner":
        raise RuntimeError("Owner financeiro incompatível com o contrato operacional.")
    return owner


def instalar(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        owner = _owner_financeiro()
        owner_quoted = schema_editor.connection.ops.quote_name(owner)
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT has_schema_privilege(%s,'public','CREATE')", [owner])
            owner_tinha_create = cursor.fetchone()[0]
        if not owner_tinha_create:
            schema_editor.execute(f"GRANT CREATE ON SCHEMA public TO {owner_quoted}")
        schema_editor.execute(f"SET LOCAL ROLE {owner_quoted}")
        schema_editor.execute(SQL.replace("__BILLING_OWNER__", owner))
        schema_editor.execute("RESET ROLE")
        if not owner_tinha_create:
            schema_editor.execute(f"REVOKE CREATE ON SCHEMA public FROM {owner_quoted}")


def remover(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        owner = _owner_financeiro()
        owner_quoted = schema_editor.connection.ops.quote_name(owner)
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT has_schema_privilege(%s,'public','CREATE')", [owner])
            owner_tinha_create = cursor.fetchone()[0]
        if not owner_tinha_create:
            schema_editor.execute(f"GRANT CREATE ON SCHEMA public TO {owner_quoted}")
        schema_editor.execute(f"SET LOCAL ROLE {owner_quoted}")
        schema_editor.execute("DROP FUNCTION public.faturamento_claim_recovery(integer,timestamptz)")
        schema_editor.execute("RESET ROLE")
        from importlib import import_module

        anterior = import_module("apps.assinaturas.subapps.faturamento.migrations.0008_fronteira_recovery_e_rls_auditoria")
        grant = "GRANT EXECUTE ON FUNCTION public.faturamento_claim_recovery(integer,timestamptz) TO billing_ingress_runtime;"
        schema_editor.execute(anterior.SQL.replace("__BILLING_OWNER__", owner).replace(grant, ""))
        schema_editor.execute(f"SET LOCAL ROLE {owner_quoted}")
        schema_editor.execute(grant)
        schema_editor.execute("RESET ROLE")
        if not owner_tinha_create:
            schema_editor.execute(f"REVOKE CREATE ON SCHEMA public FROM {owner_quoted}")


def preparar_reverse(apps, schema_editor):
    """O schema anterior representava fatos indisponíveis como zero."""
    FaturaAssinatura = apps.get_model("faturamento", "FaturaAssinatura")
    manager = FaturaAssinatura.objects.using(schema_editor.connection.alias)
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT current_user")
            papel_ddl = schema_editor.connection.ops.quote_name(cursor.fetchone()[0])
        schema_editor.execute(
            f"""
            DROP POLICY IF EXISTS faturamento_reverse_0011_fatos_nulos_select ON public.fatura_assinatura;
            DROP POLICY IF EXISTS faturamento_reverse_0011_fatos_nulos ON public.fatura_assinatura;
            CREATE POLICY faturamento_reverse_0011_fatos_nulos_select ON public.fatura_assinatura
            FOR SELECT TO {papel_ddl}
            USING (true);
            CREATE POLICY faturamento_reverse_0011_fatos_nulos ON public.fatura_assinatura
            FOR UPDATE TO {papel_ddl}
            USING (
                subtotal_centavos IS NULL OR desconto_centavos IS NULL
                OR imposto_centavos IS NULL OR total_centavos IS NULL
            )
            WITH CHECK (true);
            ALTER TABLE public.fatura_assinatura DISABLE TRIGGER fatura_assinatura_coerencia;
            UPDATE public.fatura_assinatura
            SET subtotal_centavos=COALESCE(subtotal_centavos,0),
                desconto_centavos=COALESCE(desconto_centavos,0),
                imposto_centavos=COALESCE(imposto_centavos,0),
                total_centavos=COALESCE(total_centavos,0)
            WHERE subtotal_centavos IS NULL OR desconto_centavos IS NULL
               OR imposto_centavos IS NULL OR total_centavos IS NULL;
            ALTER TABLE public.fatura_assinatura ENABLE TRIGGER fatura_assinatura_coerencia;
            DROP POLICY faturamento_reverse_0011_fatos_nulos ON public.fatura_assinatura;
            DROP POLICY faturamento_reverse_0011_fatos_nulos_select ON public.fatura_assinatura;
            SET CONSTRAINTS ALL IMMEDIATE;
            """
        )
        return
    for campo in ("subtotal_centavos", "desconto_centavos", "imposto_centavos", "total_centavos"):
        manager.filter(**{f"{campo}__isnull": True}).update(**{campo: 0})


def noop(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0010_auditoria_reconciliacao_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocobranca',
            name='recuperacao_arrendada_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturaassinatura',
            name='desconto_centavos',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturaassinatura',
            name='imposto_centavos',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturaassinatura',
            name='subtotal_centavos',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturaassinatura',
            name='total_centavos',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="eventocobranca",
            options={
                "permissions": [
                    ("retry_failed_eventocobranca", "Pode reabrir evento de cobrança falho"),
                    ("reconcile_eventocobranca", "Pode reconciliar evento de cobrança"),
                ]
            },
        ),
        migrations.RunPython(noop, preparar_reverse),
        migrations.RunPython(instalar, remover),
    ]
