# Generated by Django 5.2.8 on 2026-07-22 16:59

import apps.organizacoes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'db_table': 'organizacao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('papel', models.PositiveSmallIntegerField(choices=[(10, 'Visualizador'), (20, 'Membro'), (30, 'Gestor'), (40, 'Administrador'), (50, 'Proprietário')], default=20, verbose_name='papel')),
                ('token', models.CharField(default=apps.organizacoes.models.gerar_token_convite, editable=False, max_length=100, unique=True, verbose_name='token')),
                ('expira_em', models.DateTimeField(default=apps.organizacoes.models.expiracao_padrao_convite, verbose_name='expira em')),
                ('aceito_em', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
                ('convidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL, verbose_name='convidado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='organizacoes.organizacao', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'db_table': 'convite',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='organizacoes.organizacao', verbose_name='organização')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'db_table': 'time',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='hora de criação')),
                ('data_ultima_alteracao', models.DateField(auto_now=True, verbose_name='data da última alteração')),
                ('hora_ultima_alteracao', models.TimeField(auto_now=True, verbose_name='hora da última alteração')),
                ('papel', models.PositiveSmallIntegerField(choices=[(10, 'Visualizador'), (20, 'Membro'), (30, 'Gestor'), (40, 'Administrador'), (50, 'Proprietário')], default=20, verbose_name='papel')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='organizacoes.organizacao', verbose_name='organização')),
                ('times', models.ManyToManyField(blank=True, related_name='vinculos', to='organizacoes.time', verbose_name='times')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'db_table': 'vinculo',
                'ordering': ['-papel'],
            },
        ),
        migrations.AddConstraint(
            model_name='time',
            constraint=models.UniqueConstraint(fields=('organizacao', 'nome'), name='time_unico_por_organizacao'),
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(fields=('organizacao', 'usuario'), name='vinculo_unico_por_organizacao'),
        ),
    ]
