# Generated by Django 5.2.8 on 2026-08-15 21:05

import apps.organizacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('papel', models.PositiveSmallIntegerField(choices=[(10, 'Visualizador'), (20, 'Membro'), (30, 'Gestor'), (40, 'Administrador'), (50, 'Proprietário')], default=20, verbose_name='papel')),
                ('token', models.CharField(default=apps.organizacoes.models.gerar_token_convite, editable=False, max_length=100, verbose_name='token')),
                ('expira_em', models.DateTimeField(default=apps.organizacoes.models.expiracao_padrao_convite, verbose_name='expira em')),
                ('aceito_em', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'db_table': 'convite',
                'ordering': ['-id'],
                'permissions': [('can_accept_convite', 'Pode aceitar convite')],
            },
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(max_length=60, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'db_table': 'organizacao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'db_table': 'time',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('papel', models.PositiveSmallIntegerField(choices=[(10, 'Visualizador'), (20, 'Membro'), (30, 'Gestor'), (40, 'Administrador'), (50, 'Proprietário')], default=20, verbose_name='papel')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'db_table': 'vinculo',
                'ordering': ['-papel'],
            },
        ),
    ]
