# Generated by Django 5.2.8 on 2026-08-15 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='convidado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL, verbose_name='convidado por'),
        ),
        migrations.AddField(
            model_name='convite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='convite',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='organizacoes.organizacao', verbose_name='organização'),
        ),
        migrations.AddField(
            model_name='time',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='time',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='organizacoes.organizacao', verbose_name='organização'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='organizacoes.organizacao', verbose_name='organização'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='times',
            field=models.ManyToManyField(blank=True, related_name='vinculos', to='organizacoes.time', verbose_name='times'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddConstraint(
            model_name='organizacao',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('slug',), name='organizacao_slug_unico_nao_excluido'),
        ),
        migrations.AddConstraint(
            model_name='convite',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('token',), name='convite_token_unico_nao_excluido'),
        ),
        migrations.AddConstraint(
            model_name='time',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organizacao', 'nome'), name='time_unico_por_organizacao_nao_excluido'),
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organizacao', 'usuario'), name='vinculo_unico_por_organizacao_nao_excluido'),
        ),
    ]
