# Generated by Django 5.2.8 on 2026-07-30

import apps.organizacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="organizacao", old_name="ativo", new_name="is_active"),
        migrations.RenameField(model_name="time", old_name="ativo", new_name="is_active"),
        migrations.RenameField(model_name="vinculo", old_name="ativo", new_name="is_active"),
        migrations.RenameField(model_name="convite", old_name="ativo", new_name="is_active"),
        migrations.AddField(
            model_name="organizacao",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="excluído"),
        ),
        migrations.AddField(
            model_name="time",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="excluído"),
        ),
        migrations.AddField(
            model_name="vinculo",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="excluído"),
        ),
        migrations.AddField(
            model_name="convite",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="excluído"),
        ),
        migrations.AlterField(
            model_name="organizacao",
            name="slug",
            field=models.SlugField(max_length=60, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="convite",
            name="token",
            field=models.CharField(
                default=apps.organizacoes.models.gerar_token_convite,
                editable=False,
                max_length=100,
                verbose_name="token",
            ),
        ),
        migrations.RemoveConstraint(model_name="time", name="time_unico_por_organizacao"),
        migrations.RemoveConstraint(model_name="vinculo", name="vinculo_unico_por_organizacao"),
        migrations.AddConstraint(
            model_name="organizacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("slug",),
                name="organizacao_slug_unico_nao_excluido",
            ),
        ),
        migrations.AddConstraint(
            model_name="time",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("organizacao", "nome"),
                name="time_unico_por_organizacao_nao_excluido",
            ),
        ),
        migrations.AddConstraint(
            model_name="vinculo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("organizacao", "usuario"),
                name="vinculo_unico_por_organizacao_nao_excluido",
            ),
        ),
        migrations.AddConstraint(
            model_name="convite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("token",),
                name="convite_token_unico_nao_excluido",
            ),
        ),
    ]
