# Generated by Django 5.2.8 on 2026-08-29 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacoes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='email_faturamento',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail de faturamento'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='encerramento_agendado_para',
            field=models.DateTimeField(blank=True, null=True, verbose_name='encerramento agendado para'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='encerramento_solicitado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='encerramento solicitado em'),
        ),
        migrations.AddConstraint(
            model_name='organizacao',
            constraint=models.CheckConstraint(condition=models.Q(('encerramento_agendado_para__isnull', True), ('encerramento_solicitado_em__isnull', False), _connector='OR'), name='organizacao_agendamento_exige_solicitacao'),
        ),
    ]
