# Generated by Django 5.2.8 on 2026-09-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='current_workspace',
            field=models.ForeignKey(blank=True, db_comment='Workspace operacional atual deste vínculo.', help_text='Workspace operacional atual deste vínculo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_atuais', to='workspaces.workspace', verbose_name='workspace atual'),
        ),
    ]
