# Generated by Django 5.2.8 on 2026-08-10 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizacoes', '0003_reconcile_audit_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('object_id', models.PositiveIntegerField(verbose_name='object ID')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='data')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='contenttypes.contenttype', verbose_name='content type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'Metadata',
                'verbose_name_plural': 'Metadata',
                'db_table': 'metadata',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='metadata_content_type_object_id_unique')],
            },
        ),
    ]
