# Generated by Django 5.2.8 on 2026-08-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='object ID')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='data')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'Metadata',
                'verbose_name_plural': 'Metadata',
                'db_table': 'metadata',
                'ordering': ['-id'],
            },
        ),
    ]
