# Generated by Django 5.2.8 on 2026-08-10 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('metadata', '0001_initial'),
        ('organizacoes', '0003_reconcile_audit_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metadata',
            name='metadata_content_type_object_id_unique',
        ),
        migrations.AlterField(
            model_name='metadata',
            name='object_id',
            field=models.PositiveBigIntegerField(verbose_name='object ID'),
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organizacao', 'content_type', 'object_id'), name='metadata_organizacao_content_type_object_id_unique'),
        ),
    ]
