# Generated by Django 5.2.8 on 2026-08-15 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização'),
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organizacao', 'content_type', 'object_id'), name='metadata_organizacao_content_type_object_id_unique'),
        ),
    ]
