# Generated by Django 5.2.8 on 2026-09-24 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_initial'),
        ('workspaces', '0002_backfill_workspaces_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='workspace',
            field=models.ForeignKey(blank=True, db_comment='Workspace do registro; nulo indica compartilhamento na Organização.', help_text='Workspace do registro; vazio indica compartilhamento na Organização.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace', verbose_name='workspace'),
        ),
    ]
