# Generated by Django 5.2.8 on 2026-08-29 04:13

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('codigo', models.SlugField(max_length=60, verbose_name='código')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('visivel', models.BooleanField(default=True, verbose_name='visível')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'plano',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='VersaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='número')),
                ('atual', models.BooleanField(default=False, verbose_name='atual')),
                ('seats_inclusos', models.PositiveSmallIntegerField(default=0, verbose_name='seats inclusos')),
                ('limite_seats_trial', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='limite de seats no trial')),
                ('duracao_trial_dias', models.PositiveSmallIntegerField(default=0, verbose_name='duração do trial em dias')),
                ('carencia_pagamento_dias', models.PositiveSmallIntegerField(default=7, verbose_name='carência de pagamento em dias')),
                ('carencia_excesso_seats_dias', models.PositiveSmallIntegerField(default=7, verbose_name='carência de excesso de seats em dias')),
                ('expansao_automatica_seats', models.BooleanField(default=False, verbose_name='expansão automática de seats')),
                ('recursos', models.JSONField(default=dict, verbose_name='recursos')),
                ('publicada_em', models.DateTimeField(blank=True, null=True, verbose_name='publicada em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='assinaturas.plano', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'Versão de plano',
                'verbose_name_plural': 'Versões de plano',
                'db_table': 'versao_plano',
                'ordering': ('plano_id', '-numero'),
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PrecoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('periodicidade', models.PositiveSmallIntegerField(choices=[(10, 'Mensal'), (20, 'Anual')], verbose_name='periodicidade')),
                ('moeda', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Informe três letras maiúsculas.', regex='^[A-Z]{3}$')], verbose_name='moeda')),
                ('valor_base_centavos', models.PositiveBigIntegerField(verbose_name='valor base em centavos')),
                ('valor_seat_centavos', models.PositiveBigIntegerField(verbose_name='valor por seat em centavos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('versao_plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos', to='assinaturas.versaoplano', verbose_name='versão do plano')),
            ],
            options={
                'verbose_name': 'Preço de plano',
                'verbose_name_plural': 'Preços de plano',
                'db_table': 'preco_plano',
                'ordering': ('versao_plano_id', 'periodicidade', 'moeda'),
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='plano',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('codigo',), name='plano_codigo_unico_nao_excluido'),
        ),
        migrations.AddConstraint(
            model_name='versaoplano',
            constraint=models.UniqueConstraint(fields=('plano', 'numero'), name='versao_plano_numero_unico_por_plano'),
        ),
        migrations.AddConstraint(
            model_name='versaoplano',
            constraint=models.UniqueConstraint(condition=models.Q(('atual', True), ('is_deleted', False)), fields=('plano',), name='versao_plano_atual_unica_por_plano'),
        ),
        migrations.AddConstraint(
            model_name='precoplano',
            constraint=models.UniqueConstraint(fields=('versao_plano', 'periodicidade', 'moeda'), name='preco_plano_unico_por_versao_periodicidade_moeda'),
        ),
        migrations.AddConstraint(
            model_name='precoplano',
            constraint=models.CheckConstraint(condition=models.Q(('moeda__regex', '^[A-Z]{3}$')), name='preco_plano_moeda_iso_maiuscula'),
        ),
        migrations.AddConstraint(
            model_name='precoplano',
            constraint=models.CheckConstraint(condition=models.Q(('valor_base_centavos__gte', 0)), name='preco_plano_valor_base_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='precoplano',
            constraint=models.CheckConstraint(condition=models.Q(('valor_seat_centavos__gte', 0)), name='preco_plano_valor_seat_nao_negativo'),
        ),
    ]
