# Generated by Django 5.2.8 on 2026-08-29 15:59

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


CRIAR_PROTECAO_ALTERACAO = """
CREATE OR REPLACE FUNCTION proteger_historico_alteracao_assinatura()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Pedido e snapshots da alteração são imutáveis.';
    END IF;

    IF (
        to_jsonb(NEW) - ARRAY[
            'status',
            'processada_em',
            'aplicada_em',
            'evento_gateway',
            'falha_codigo',
            'falha_mensagem',
            'revisao_aplicada',
            'revisao_observada',
            'ignorada_em',
            'last_modified_at'
        ]
    ) IS DISTINCT FROM (
        to_jsonb(OLD) - ARRAY[
            'status',
            'processada_em',
            'aplicada_em',
            'evento_gateway',
            'falha_codigo',
            'falha_mensagem',
            'revisao_aplicada',
            'revisao_observada',
            'ignorada_em',
            'last_modified_at'
        ]
    ) THEN
        RAISE EXCEPTION 'Pedido e snapshots da alteração são imutáveis.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER alteracao_assinatura_historico_imutavel
BEFORE UPDATE OR DELETE ON alteracao_assinatura
FOR EACH ROW EXECUTE FUNCTION proteger_historico_alteracao_assinatura();
"""

REMOVER_PROTECAO_ALTERACAO = """
DROP TRIGGER IF EXISTS alteracao_assinatura_historico_imutavel ON alteracao_assinatura;
DROP FUNCTION IF EXISTS proteger_historico_alteracao_assinatura();
"""


def criar_protecao_alteracao(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(CRIAR_PROTECAO_ALTERACAO)


def remover_protecao_alteracao(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REMOVER_PROTECAO_ALTERACAO)


def habilitar_rls_contratos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    expressao = "organizacao_id = (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::integer)"
    for tabela in ("assinatura_organizacao", "alteracao_assinatura"):
        schema_editor.execute(f'ALTER TABLE "{tabela}" ENABLE ROW LEVEL SECURITY')
        schema_editor.execute(f'ALTER TABLE "{tabela}" FORCE ROW LEVEL SECURITY')
        schema_editor.execute(
            f'CREATE POLICY "isolamento_organizacao" ON "{tabela}" '
            f"USING ({expressao}) WITH CHECK ({expressao})"
        )


def desabilitar_rls_contratos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for tabela in ("alteracao_assinatura", "assinatura_organizacao"):
        schema_editor.execute(f'DROP POLICY IF EXISTS "isolamento_organizacao" ON "{tabela}"')
        schema_editor.execute(f'ALTER TABLE "{tabela}" NO FORCE ROW LEVEL SECURITY')
        schema_editor.execute(f'ALTER TABLE "{tabela}" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0004_ordenar_locks_catalogo'),
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaOrganizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Pendente'), (20, 'Em trial'), (30, 'Ativa'), (40, 'Encerrada')], verbose_name='status')),
                ('status_financeiro', models.PositiveSmallIntegerField(choices=[(10, 'Isento'), (20, 'Pendente'), (30, 'Regular'), (40, 'Inadimplente'), (50, 'Irrecuperável')], verbose_name='status financeiro')),
                ('revisao', models.PositiveSmallIntegerField(default=1, verbose_name='revisão')),
                ('periodicidade', models.PositiveSmallIntegerField(choices=[(10, 'Mensal'), (20, 'Anual')], verbose_name='periodicidade')),
                ('moeda', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Informe três letras maiúsculas.', regex='^[A-Z]{3}$')], verbose_name='moeda')),
                ('valor_base_centavos', models.PositiveBigIntegerField(verbose_name='valor base em centavos')),
                ('valor_seat_centavos', models.PositiveBigIntegerField(verbose_name='valor por seat em centavos')),
                ('seats_inclusos', models.PositiveSmallIntegerField(default=0, verbose_name='seats inclusos')),
                ('seats_contratados', models.PositiveSmallIntegerField(default=0, verbose_name='seats contratados')),
                ('expansao_automatica_seats', models.BooleanField(default=False, verbose_name='expansão automática de seats')),
                ('recursos', models.JSONField(default=dict, verbose_name='recursos')),
                ('politica_trial', models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Sem forma de pagamento'), (20, 'Com forma de pagamento')], null=True, verbose_name='política de trial')),
                ('trial_iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='trial iniciado em')),
                ('trial_termina_em', models.DateTimeField(blank=True, null=True, verbose_name='trial termina em')),
                ('periodo_atual_iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='período atual iniciado em')),
                ('periodo_atual_termina_em', models.DateTimeField(blank=True, null=True, verbose_name='período atual termina em')),
                ('carencia_pagamento_dias', models.PositiveSmallIntegerField(default=0, verbose_name='carência de pagamento em dias')),
                ('carencia_pagamento_iniciada_em', models.DateTimeField(blank=True, null=True, verbose_name='carência de pagamento iniciada em')),
                ('carencia_pagamento_termina_em', models.DateTimeField(blank=True, null=True, verbose_name='carência de pagamento termina em')),
                ('carencia_excesso_seats_dias', models.PositiveSmallIntegerField(default=0, verbose_name='carência de excesso de seats em dias')),
                ('carencia_excesso_seats_iniciada_em', models.DateTimeField(blank=True, null=True, verbose_name='carência de excesso de seats iniciada em')),
                ('carencia_excesso_seats_termina_em', models.DateTimeField(blank=True, null=True, verbose_name='carência de excesso de seats termina em')),
                ('cancelamento_agendado_para', models.DateTimeField(blank=True, null=True, verbose_name='cancelamento agendado para')),
                ('encerrada_em', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('motivo_encerramento', models.CharField(blank=True, max_length=100, null=True, verbose_name='motivo do encerramento')),
                ('chave_idempotencia', models.CharField(max_length=120, verbose_name='chave de idempotência')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização')),
                ('versao_plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_organizacoes', to='assinaturas.versaoplano', verbose_name='versão do plano')),
            ],
            options={
                'verbose_name': 'Assinatura da organização',
                'verbose_name_plural': 'Assinaturas das organizações',
                'db_table': 'assinatura_organizacao',
                'ordering': ('-created_at', '-pk'),
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AlteracaoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(10, 'Upgrade de plano'), (20, 'Aumento de seats'), (30, 'Downgrade de plano'), (40, 'Redução de seats'), (50, 'Mudança de periodicidade')], verbose_name='tipo')),
                ('momento_aplicacao', models.PositiveSmallIntegerField(choices=[(10, 'Imediata'), (20, 'Próximo ciclo')], verbose_name='momento de aplicação')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Solicitada'), (20, 'Aguardando gateway'), (30, 'Confirmada'), (40, 'Falhou'), (50, 'Cancelada')], default=10, verbose_name='status')),
                ('revisao_esperada', models.PositiveSmallIntegerField(verbose_name='revisão esperada')),
                ('chave_idempotencia', models.CharField(max_length=120, verbose_name='chave de idempotência')),
                ('pedido', models.JSONField(verbose_name='pedido')),
                ('snapshot_anterior', models.JSONField(verbose_name='snapshot anterior')),
                ('snapshot_pretendido', models.JSONField(verbose_name='snapshot pretendido')),
                ('aplicar_em', models.DateTimeField(blank=True, null=True, verbose_name='aplicar em')),
                ('processada_em', models.DateTimeField(blank=True, null=True, verbose_name='processada em')),
                ('aplicada_em', models.DateTimeField(blank=True, null=True, verbose_name='aplicada em')),
                ('evento_gateway', models.CharField(blank=True, max_length=255, null=True, verbose_name='evento do gateway')),
                ('falha_codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='código da falha')),
                ('falha_mensagem', models.CharField(blank=True, max_length=500, null=True, verbose_name='mensagem da falha')),
                ('revisao_aplicada', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='revisão aplicada')),
                ('revisao_observada', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='revisão observada')),
                ('ignorada_em', models.DateTimeField(blank=True, null=True, verbose_name='ignorada em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização')),
                ('solicitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes_assinatura_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes', to='assinaturas.assinaturaorganizacao', verbose_name='assinatura')),
            ],
            options={
                'verbose_name': 'Alteração de assinatura',
                'verbose_name_plural': 'Alterações de assinatura',
                'db_table': 'alteracao_assinatura',
                'ordering': ('-created_at', '-pk'),
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='assinaturaorganizacao',
            index=models.Index(fields=['organizacao', 'status'], name='assinatura_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(('versao_plano__isnull', False)), name='assinatura_origem_catalogo_exige_versao'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.UniqueConstraint(fields=('organizacao', 'chave_idempotencia'), name='assinatura_org_chave_idempotencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', (10, 20, 30))), fields=('organizacao',), name='assinatura_org_contrato_corrente_unico'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('encerrada_em__isnull', False), ('motivo_encerramento__isnull', False), ('status', 40), models.Q(('motivo_encerramento', ''), _negated=True)), models.Q(models.Q(('status', 40), _negated=True), ('encerrada_em__isnull', True), ('motivo_encerramento__isnull', True)), _connector='OR'), name='assinatura_encerramento_coerente'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('politica_trial__isnull', False), ('status', 20), ('trial_iniciado_em__isnull', False), ('trial_iniciado_em__lt', models.F('trial_termina_em')), ('trial_termina_em__isnull', False)), models.Q(('status__in', (30, 40)), models.Q(models.Q(('politica_trial__isnull', True), ('trial_iniciado_em__isnull', True), ('trial_termina_em__isnull', True)), models.Q(('politica_trial__isnull', False), ('trial_iniciado_em__isnull', False), ('trial_iniciado_em__lt', models.F('trial_termina_em')), ('trial_termina_em__isnull', False)), _connector='OR')), models.Q(('politica_trial__isnull', True), ('status', 10), ('trial_iniciado_em__isnull', True), ('trial_termina_em__isnull', True)), _connector='OR'), name='assinatura_trial_coerente'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('periodo_atual_iniciado_em__isnull', True), ('periodo_atual_termina_em__isnull', True)), models.Q(('periodo_atual_iniciado_em__isnull', False), ('periodo_atual_iniciado_em__lt', models.F('periodo_atual_termina_em')), ('periodo_atual_termina_em__isnull', False)), _connector='OR'), name='assinatura_periodo_atual_coerente'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carencia_pagamento_iniciada_em__isnull', True), ('carencia_pagamento_termina_em__isnull', True)), models.Q(('carencia_pagamento_iniciada_em__isnull', False), ('carencia_pagamento_iniciada_em__lte', models.F('carencia_pagamento_termina_em')), ('carencia_pagamento_termina_em__isnull', False)), _connector='OR'), name='assinatura_carencia_pagamento_coerente'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carencia_excesso_seats_iniciada_em__isnull', True), ('carencia_excesso_seats_termina_em__isnull', True)), models.Q(('carencia_excesso_seats_iniciada_em__isnull', False), ('carencia_excesso_seats_iniciada_em__lte', models.F('carencia_excesso_seats_termina_em')), ('carencia_excesso_seats_termina_em__isnull', False)), _connector='OR'), name='assinatura_carencia_seats_coerente'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 10), ('status_financeiro', 20)), models.Q(('status', 20), ('status_financeiro', 10)), models.Q(('status', 30), ('status_financeiro__in', (10, 30, 40, 50))), ('status', 40), _connector='OR'), name='assinatura_status_financeiro_coerente'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(('moeda__regex', '^[A-Z]{3}$')), name='assinatura_moeda_iso_maiuscula'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(('revisao__gte', 1)), name='assinatura_revisao_positiva'),
        ),
        migrations.AddIndex(
            model_name='alteracaoassinatura',
            index=models.Index(fields=['organizacao', 'assinatura', 'status'], name='alteracao_org_ass_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.UniqueConstraint(fields=('organizacao', 'chave_idempotencia'), name='alteracao_org_chave_idempotencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(('revisao_esperada__gte', 1)), name='alteracao_revisao_esperada_positiva'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(('momento_aplicacao', 10), ('aplicar_em__isnull', False), _connector='OR'), name='alteracao_proximo_ciclo_exige_data'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aplicada_em__isnull', True), ('revisao_aplicada__isnull', True)), models.Q(('aplicada_em__isnull', False), ('revisao_aplicada', django.db.models.expressions.CombinedExpression(models.F('revisao_esperada'), '+', models.Value(1))), ('revisao_aplicada__isnull', False), ('status', 30)), _connector='OR'), name='alteracao_aplicacao_coerente'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ignorada_em__isnull', True), ('revisao_observada__isnull', True)), models.Q(('aplicada_em__isnull', True), ('ignorada_em__isnull', False), ('processada_em__isnull', False), ('revisao_observada__isnull', False), ('status', 30)), _connector='OR'), name='alteracao_evento_ignorado_coerente'),
        ),
        migrations.RunPython(criar_protecao_alteracao, remover_protecao_alteracao),
        migrations.RunPython(habilitar_rls_contratos, desabilitar_rls_contratos),
    ]
