# Generated by Django 5.2.8 on 2026-08-29 17:05

from django.db import migrations, models


CRIAR_GUARDAS_POSTGRESQL = """
CREATE OR REPLACE FUNCTION validar_tenant_alteracao_assinatura()
RETURNS trigger AS $$
DECLARE
    organizacao_da_assinatura bigint;
BEGIN
    SELECT organizacao_id
      INTO organizacao_da_assinatura
      FROM assinatura_organizacao
     WHERE id = NEW.assinatura_id;

    IF organizacao_da_assinatura IS NULL OR organizacao_da_assinatura <> NEW.organizacao_id THEN
        RAISE EXCEPTION 'A organização da assinatura diverge da alteração.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER alteracao_assinatura_coerencia_tenant
BEFORE INSERT OR UPDATE ON alteracao_assinatura
FOR EACH ROW EXECUTE FUNCTION validar_tenant_alteracao_assinatura();

CREATE OR REPLACE FUNCTION validar_transicao_status_alteracao_assinatura()
RETURNS trigger AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status AND NOT (
        (OLD.status = 10 AND NEW.status IN (20, 30, 40, 50)) OR
        (OLD.status = 20 AND NEW.status IN (30, 40, 50)) OR
        (OLD.status = 30 AND NEW.status = 50)
    ) THEN
        RAISE EXCEPTION 'Transição inválida de status da alteração.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER alteracao_assinatura_transicao_status
BEFORE UPDATE ON alteracao_assinatura
FOR EACH ROW EXECUTE FUNCTION validar_transicao_status_alteracao_assinatura();

CREATE OR REPLACE FUNCTION validar_transicao_status_assinatura()
RETURNS trigger AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status AND NOT (
        (OLD.status = 10 AND NEW.status IN (30, 40)) OR
        (OLD.status = 20 AND NEW.status IN (30, 40)) OR
        (OLD.status = 30 AND NEW.status = 40)
    ) THEN
        RAISE EXCEPTION 'Transição inválida de status da assinatura.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER assinatura_organizacao_transicao_status
BEFORE UPDATE ON assinatura_organizacao
FOR EACH ROW EXECUTE FUNCTION validar_transicao_status_assinatura();
"""

REMOVER_GUARDAS_POSTGRESQL = """
DROP TRIGGER IF EXISTS assinatura_organizacao_transicao_status ON assinatura_organizacao;
DROP FUNCTION IF EXISTS validar_transicao_status_assinatura();
DROP TRIGGER IF EXISTS alteracao_assinatura_transicao_status ON alteracao_assinatura;
DROP FUNCTION IF EXISTS validar_transicao_status_alteracao_assinatura();
DROP TRIGGER IF EXISTS alteracao_assinatura_coerencia_tenant ON alteracao_assinatura;
DROP FUNCTION IF EXISTS validar_tenant_alteracao_assinatura();
"""


def criar_guardas_postgresql(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(CRIAR_GUARDAS_POSTGRESQL)


def remover_guardas_postgresql(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REMOVER_GUARDAS_POSTGRESQL)


def _recriar_policies_rls(schema_editor, *, tipo_tenant):
    for tabela in ("assinatura_organizacao", "alteracao_assinatura"):
        schema_editor.execute(f'DROP POLICY IF EXISTS "isolamento_organizacao" ON "{tabela}"')
        expressao = f"organizacao_id = (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::{tipo_tenant})"
        schema_editor.execute(
            f'CREATE POLICY "isolamento_organizacao" ON "{tabela}" '
            f"USING ({expressao}) WITH CHECK ({expressao})"
        )


def usar_bigint_nas_policies_rls(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        _recriar_policies_rls(schema_editor, tipo_tenant="bigint")


def restaurar_integer_nas_policies_rls(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        _recriar_policies_rls(schema_editor, tipo_tenant="integer")


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0005_assinaturaorganizacao_alteracaoassinatura_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alteracaoassinatura',
            name='alteracao_proximo_ciclo_exige_data',
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aplicar_em__isnull', True), ('momento_aplicacao', 10)), models.Q(('aplicar_em__gt', models.F('created_at')), ('aplicar_em__isnull', False), ('momento_aplicacao', 20)), _connector='OR'), name='alteracao_momento_data_coerente'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', [10, 20, 30, 40, 50])), name='alteracao_tipo_dominio'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(('momento_aplicacao__in', [10, 20])), name='alteracao_momento_dominio'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [10, 20, 30, 40, 50])), name='alteracao_status_dominio'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aplicada_em__isnull', True), ('evento_gateway__isnull', True), ('falha_codigo__isnull', True), ('falha_mensagem__isnull', True), ('ignorada_em__isnull', True), ('processada_em__isnull', True), ('revisao_aplicada__isnull', True), ('revisao_observada__isnull', True), ('status__in', (10, 20))), models.Q(('falha_codigo__isnull', True), ('falha_mensagem__isnull', True), ('processada_em__isnull', False), ('status', 30), models.Q(models.Q(('aplicada_em__isnull', False), ('ignorada_em__isnull', True), ('revisao_aplicada__isnull', False), ('revisao_observada__isnull', True)), models.Q(('aplicada_em__isnull', True), ('ignorada_em__isnull', True), ('momento_aplicacao', 20), ('revisao_aplicada__isnull', True), ('revisao_observada__isnull', True)), models.Q(('aplicada_em__isnull', True), ('ignorada_em__isnull', False), ('revisao_aplicada__isnull', True), ('revisao_observada__isnull', False)), _connector='OR')), models.Q(('aplicada_em__isnull', True), ('falha_codigo__isnull', False), ('falha_mensagem__isnull', False), ('ignorada_em__isnull', True), ('processada_em__isnull', False), ('revisao_aplicada__isnull', True), ('revisao_observada__isnull', True), ('status', 40), models.Q(('falha_codigo', ''), _negated=True), models.Q(('falha_mensagem', ''), _negated=True)), models.Q(('aplicada_em__isnull', True), ('falha_codigo__isnull', True), ('falha_mensagem__isnull', True), ('ignorada_em__isnull', True), ('processada_em__isnull', False), ('revisao_aplicada__isnull', True), ('revisao_observada__isnull', True), ('status', 50)), _connector='OR'), name='alteracao_processamento_coerente'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [10, 20, 30, 40])), name='assinatura_status_dominio'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(('status_financeiro__in', [10, 20, 30, 40, 50])), name='assinatura_financeiro_dominio'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(('periodicidade__in', [10, 20])), name='assinatura_periodicidade_dominio'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(('politica_trial__isnull', True), ('politica_trial__in', [10, 20]), _connector='OR'), name='assinatura_politica_trial_dominio'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(('cancelamento_agendado_para__isnull', True), models.Q(('cancelamento_agendado_para', models.F('periodo_atual_termina_em')), ('periodo_atual_termina_em__isnull', False), ('status', 30)), _connector='OR'), name='assinatura_cancelamento_agendado_coerente'),
        ),
        migrations.RunPython(criar_guardas_postgresql, remover_guardas_postgresql),
        migrations.RunPython(usar_bigint_nas_policies_rls, restaurar_integer_nas_policies_rls),
    ]
