# Generated by Django 5.2.8 on 2026-08-29 19:43

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


CRIAR_GUARDAS_PROPOSTA = """
CREATE OR REPLACE FUNCTION proteger_snapshot_proposta_comercial()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Os termos e a identidade da proposta são imutáveis.';
    END IF;

    IF (
        NEW.id,
        NEW.organizacao_id,
        NEW.created_at,
        NEW.created_by_id
    ) IS DISTINCT FROM (
        OLD.id,
        OLD.organizacao_id,
        OLD.created_at,
        OLD.created_by_id
    ) THEN
        RAISE EXCEPTION 'Os termos e a identidade da proposta são imutáveis.';
    END IF;

    IF (OLD.status <> 10 OR NEW.status <> 10) AND (
        to_jsonb(NEW) - ARRAY[
            'status',
            'revisao',
            'enviada_em',
            'aceita_em',
            'aceita_por_id',
            'ativada_em',
            'ativada_por_id',
            'justificativa_ativacao',
            'recusada_em',
            'recusada_por_id',
            'expirada_em',
            'cancelada_em',
            'cancelada_por_id',
            'is_active',
            'last_modified_at'
        ]
    ) IS DISTINCT FROM (
        to_jsonb(OLD) - ARRAY[
            'status',
            'revisao',
            'enviada_em',
            'aceita_em',
            'aceita_por_id',
            'ativada_em',
            'ativada_por_id',
            'justificativa_ativacao',
            'recusada_em',
            'recusada_por_id',
            'expirada_em',
            'cancelada_em',
            'cancelada_por_id',
            'is_active',
            'last_modified_at'
        ]
    ) THEN
        RAISE EXCEPTION 'Os termos de uma proposta enviada são imutáveis.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER proposta_comercial_snapshot_imutavel
BEFORE UPDATE OR DELETE ON proposta_comercial
FOR EACH ROW EXECUTE FUNCTION proteger_snapshot_proposta_comercial();

CREATE OR REPLACE FUNCTION validar_tenant_proposta_assinatura()
RETURNS trigger AS $$
DECLARE
    organizacao_da_proposta bigint;
BEGIN
    IF NEW.proposta_comercial_id IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT organizacao_id
      INTO organizacao_da_proposta
      FROM proposta_comercial
     WHERE id = NEW.proposta_comercial_id;

    IF organizacao_da_proposta IS NULL OR organizacao_da_proposta <> NEW.organizacao_id THEN
        RAISE EXCEPTION 'A organização da proposta diverge da assinatura.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER assinatura_organizacao_coerencia_proposta
BEFORE INSERT OR UPDATE ON assinatura_organizacao
FOR EACH ROW EXECUTE FUNCTION validar_tenant_proposta_assinatura();

CREATE OR REPLACE FUNCTION proteger_tenant_proposta_vinculada()
RETURNS trigger AS $$
BEGIN
    IF OLD.organizacao_id IS DISTINCT FROM NEW.organizacao_id AND EXISTS (
        SELECT 1
          FROM assinatura_organizacao
         WHERE proposta_comercial_id = OLD.id
           AND organizacao_id <> NEW.organizacao_id
    ) THEN
        RAISE EXCEPTION 'A organização da proposta diverge da assinatura.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER proposta_comercial_coerencia_assinatura
BEFORE UPDATE ON proposta_comercial
FOR EACH ROW EXECUTE FUNCTION proteger_tenant_proposta_vinculada();
"""

REMOVER_GUARDAS_PROPOSTA = """
DROP TRIGGER IF EXISTS proposta_comercial_coerencia_assinatura ON proposta_comercial;
DROP FUNCTION IF EXISTS proteger_tenant_proposta_vinculada();
DROP TRIGGER IF EXISTS assinatura_organizacao_coerencia_proposta ON assinatura_organizacao;
DROP FUNCTION IF EXISTS validar_tenant_proposta_assinatura();
DROP TRIGGER IF EXISTS proposta_comercial_snapshot_imutavel ON proposta_comercial;
DROP FUNCTION IF EXISTS proteger_snapshot_proposta_comercial();
"""


def criar_guardas_proposta(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(CRIAR_GUARDAS_PROPOSTA)


def remover_guardas_proposta(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REMOVER_GUARDAS_PROPOSTA)


def criar_constraint_recursos_proposta(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE proposta_comercial ADD CONSTRAINT proposta_recursos_objeto_json "
            "CHECK (jsonb_typeof(recursos) = 'object')"
        )


def remover_constraint_recursos_proposta(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE proposta_comercial DROP CONSTRAINT proposta_recursos_objeto_json")


def habilitar_rls_proposta(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    expressao = "organizacao_id = (SELECT NULLIF(current_setting('rls.tenant_id', true), '')::bigint)"
    schema_editor.execute('ALTER TABLE "proposta_comercial" ENABLE ROW LEVEL SECURITY')
    schema_editor.execute('ALTER TABLE "proposta_comercial" FORCE ROW LEVEL SECURITY')
    schema_editor.execute(
        'CREATE POLICY "isolamento_organizacao" ON "proposta_comercial" '
        f"USING ({expressao}) WITH CHECK ({expressao})"
    )


def desabilitar_rls_proposta(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute('DROP POLICY IF EXISTS "isolamento_organizacao" ON "proposta_comercial"')
    schema_editor.execute('ALTER TABLE "proposta_comercial" NO FORCE ROW LEVEL SECURITY')
    schema_editor.execute('ALTER TABLE "proposta_comercial" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0006_reforcar_invariantes_assinaturas'),
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Rascunho'), (20, 'Enviada'), (30, 'Aceita'), (40, 'Ativada'), (50, 'Recusada'), (60, 'Expirada'), (70, 'Cancelada')], default=10, verbose_name='status')),
                ('modo_ativacao', models.PositiveSmallIntegerField(choices=[(10, 'Pagamento'), (20, 'Contratual')], verbose_name='modo de ativacao')),
                ('revisao', models.PositiveSmallIntegerField(default=1, verbose_name='revisao')),
                ('periodicidade', models.PositiveSmallIntegerField(choices=[(10, 'Mensal'), (20, 'Anual')], verbose_name='periodicidade')),
                ('moeda', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Informe tres letras maiusculas.', regex='^[A-Z]{3}$')], verbose_name='moeda')),
                ('valor_base_centavos', models.PositiveBigIntegerField(verbose_name='valor base em centavos')),
                ('valor_seat_centavos', models.PositiveBigIntegerField(verbose_name='valor por seat em centavos')),
                ('seats_inclusos', models.PositiveSmallIntegerField(default=0, verbose_name='seats inclusos')),
                ('seats_contratados', models.PositiveSmallIntegerField(default=0, verbose_name='seats contratados')),
                ('expansao_automatica_seats', models.BooleanField(default=False, verbose_name='expansao automatica de seats')),
                ('recursos', models.JSONField(default=dict, verbose_name='recursos')),
                ('carencia_pagamento_dias', models.PositiveSmallIntegerField(default=0, verbose_name='carencia de pagamento em dias')),
                ('carencia_excesso_seats_dias', models.PositiveSmallIntegerField(default=0, verbose_name='carencia de excesso de seats em dias')),
                ('valida_ate', models.DateTimeField(verbose_name='valida ate')),
                ('enviada_em', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('aceita_em', models.DateTimeField(blank=True, null=True, verbose_name='aceita em')),
                ('ativada_em', models.DateTimeField(blank=True, null=True, verbose_name='ativada em')),
                ('justificativa_ativacao', models.TextField(blank=True, default='', verbose_name='justificativa da ativacao')),
                ('recusada_em', models.DateTimeField(blank=True, null=True, verbose_name='recusada em')),
                ('expirada_em', models.DateTimeField(blank=True, null=True, verbose_name='expirada em')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
            ],
            options={
                'verbose_name': 'Proposta comercial',
                'verbose_name_plural': 'Propostas comerciais',
                'permissions': (('activate_contractual_propostacomercial', 'Pode ativar proposta comercial contratual'),),
                'db_table': 'proposta_comercial',
                'ordering': ('-created_at', '-pk'),
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='assinaturaorganizacao',
            name='assinatura_origem_catalogo_exige_versao',
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='aceita_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_comerciais_aceitas', to=settings.AUTH_USER_MODEL, verbose_name='aceita por'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='ativada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_comerciais_ativadas', to=settings.AUTH_USER_MODEL, verbose_name='ativada por'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_comerciais_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='cancelada por'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizacoes.organizacao', verbose_name='organização'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='recusada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_comerciais_recusadas', to=settings.AUTH_USER_MODEL, verbose_name='recusada por'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='versao_plano_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_comerciais', to='assinaturas.versaoplano', verbose_name='versao do plano de referencia'),
        ),
        migrations.AddField(
            model_name='assinaturaorganizacao',
            name='proposta_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_organizacoes', to='assinaturas.propostacomercial', verbose_name='proposta comercial'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaorganizacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('proposta_comercial__isnull', True), ('versao_plano__isnull', False)), models.Q(('proposta_comercial__isnull', False), ('versao_plano__isnull', True)), _connector='OR'), name='assinatura_origem_xor'),
        ),
        migrations.AddIndex(
            model_name='propostacomercial',
            index=models.Index(fields=['organizacao', 'status', 'valida_ate'], name='proposta_org_status_val_idx'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [10, 20, 30, 40, 50, 60, 70])), name='proposta_status_dominio'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('modo_ativacao__in', [10, 20])), name='proposta_modo_dominio'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('periodicidade__in', [10, 20])), name='proposta_periodicidade_dominio'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('revisao__gte', 1)), name='proposta_revisao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('moeda__regex', '^[A-Z]{3}$')), name='proposta_moeda_iso_maiuscula'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('valor_base_centavos__gte', 0)), name='proposta_valor_base_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('valor_seat_centavos__gte', 0)), name='proposta_valor_seat_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('seats_inclusos__gte', 0)), name='proposta_seats_inclusos_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('seats_contratados__gte', 0)), name='proposta_seats_contratados_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('carencia_pagamento_dias__gte', 0)), name='proposta_carencia_pagamento_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(('carencia_excesso_seats_dias__gte', 0)), name='proposta_carencia_seats_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True), ('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('enviada_em__isnull', True), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True), ('status', 10)), models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True), ('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('enviada_em__isnull', False), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True), ('status', 20)), models.Q(('aceita_em__isnull', False), ('aceita_por__isnull', False), ('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('enviada_em__isnull', False), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True), ('status', 30)), models.Q(('aceita_em__isnull', False), ('aceita_por__isnull', False), ('ativada_em__isnull', False), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('enviada_em__isnull', False), ('expirada_em__isnull', True), ('recusada_em__isnull', True), ('recusada_por__isnull', True), ('status', 40), models.Q(models.Q(('ativada_por__isnull', True), ('justificativa_ativacao', ''), ('modo_ativacao', 10)), models.Q(('ativada_por__isnull', False), ('modo_ativacao', 20), models.Q(('justificativa_ativacao', ''), _negated=True)), _connector='OR')), models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True), ('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('enviada_em__isnull', False), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', False), ('recusada_por__isnull', False), ('status', 50)), models.Q(('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('enviada_em__isnull', False), ('expirada_em__isnull', False), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True), ('status', 60), models.Q(models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True)), models.Q(('aceita_em__isnull', False), ('aceita_por__isnull', False)), _connector='OR')), models.Q(('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', False), ('cancelada_por__isnull', False), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True), ('status', 70), models.Q(models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True)), models.Q(('aceita_em__isnull', False), ('aceita_por__isnull', False)), _connector='OR')), _connector='OR'), name='proposta_estado_datas_coerente'),
        ),
        migrations.RunPython(criar_constraint_recursos_proposta, remover_constraint_recursos_proposta),
        migrations.RunPython(criar_guardas_proposta, remover_guardas_proposta),
        migrations.RunPython(habilitar_rls_proposta, desabilitar_rls_proposta),
    ]
