# Generated by Django 5.2.8 on 2026-08-31 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0009_proteger_estado_inicial_proposta'),
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alteracaoassinatura',
            name='alteracao_tipo_dominio',
        ),
        migrations.AlterField(
            model_name='alteracaoassinatura',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Upgrade de plano'), (20, 'Aumento de seats'), (30, 'Downgrade de plano'), (40, 'Redução de seats'), (50, 'Mudança de periodicidade'), (60, 'Fallback de trial')], verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', [10, 20, 30, 40, 50, 60])), name='alteracao_tipo_dominio'),
        ),
    ]
