# Generated by Django 5.2.8 on 2026-08-31 03:34

from django.conf import settings
from django.db import migrations, models


ENDURECER_TRANSICOES_ACESSO_POSTGRESQL = """
DROP TRIGGER IF EXISTS assinatura_organizacao_transicao_status ON assinatura_organizacao;

CREATE OR REPLACE FUNCTION validar_fallback_trial_alteracao()
RETURNS trigger AS $$
DECLARE
    status_assinatura smallint;
    revisao_assinatura smallint;
BEGIN
    IF NEW.tipo <> 60 THEN
        RETURN NEW;
    END IF;

    SELECT status, revisao
      INTO status_assinatura, revisao_assinatura
      FROM assinatura_organizacao
     WHERE id = NEW.assinatura_id;

    IF status_assinatura IS DISTINCT FROM 20 OR revisao_assinatura IS DISTINCT FROM NEW.revisao_esperada THEN
        RAISE EXCEPTION 'Fallback de trial exige o contrato corrente em trial e a revisão vigente.' USING ERRCODE = '23514';
    END IF;

    IF NEW.momento_aplicacao <> 10 OR NEW.solicitada_por_id IS NOT NULL OR NEW.status <> 10 THEN
        RAISE EXCEPTION 'Fallback de trial só pode nascer pela transição nominal imediata.' USING ERRCODE = '23514';
    END IF;

    IF jsonb_typeof(NEW.pedido) IS DISTINCT FROM 'object'
       OR NEW.pedido->>'motivo' IS NULL
       OR NEW.pedido->>'motivo' NOT IN ('local_trial_ended', 'missing_valid_payment', 'first_charge_failed')
       OR (NEW.pedido->>'assinatura_id')::bigint IS DISTINCT FROM NEW.assinatura_id
       OR NEW.pedido->>'versao_plano_id' IS NULL
       OR jsonb_typeof(NEW.snapshot_anterior) IS DISTINCT FROM 'object'
       OR (NEW.snapshot_anterior->>'status')::smallint IS DISTINCT FROM 20
       OR (NEW.snapshot_anterior->>'revisao')::smallint IS DISTINCT FROM revisao_assinatura
       OR jsonb_typeof(NEW.snapshot_pretendido) IS DISTINCT FROM 'object'
       OR (NEW.snapshot_pretendido->>'status')::smallint IS DISTINCT FROM 30
       OR (NEW.snapshot_pretendido->>'status_financeiro')::smallint IS DISTINCT FROM 10
       OR (NEW.snapshot_pretendido->>'revisao')::smallint IS DISTINCT FROM revisao_assinatura + 1
       OR NEW.snapshot_pretendido->'carencia_pagamento_iniciada_em' IS DISTINCT FROM 'null'::jsonb
       OR NEW.snapshot_pretendido->'carencia_pagamento_termina_em' IS DISTINCT FROM 'null'::jsonb THEN
        RAISE EXCEPTION 'Fallback de trial diverge dos snapshots da transição nominal.' USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS alteracao_assinatura_validar_fallback_trial ON alteracao_assinatura;
CREATE TRIGGER alteracao_assinatura_validar_fallback_trial
BEFORE INSERT ON alteracao_assinatura
FOR EACH ROW EXECUTE FUNCTION validar_fallback_trial_alteracao();

CREATE OR REPLACE FUNCTION validar_transicao_status_assinatura()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF OLD.status IS DISTINCT FROM NEW.status AND NOT (
            (OLD.status = 10 AND NEW.status IN (30, 40)) OR
            (OLD.status = 20 AND NEW.status IN (30, 40)) OR
            (OLD.status = 30 AND NEW.status = 40)
        ) THEN
            RAISE EXCEPTION 'Transição inválida de status da assinatura.' USING ERRCODE = '23514';
        END IF;

        IF (
            OLD.carencia_pagamento_iniciada_em,
            OLD.carencia_pagamento_termina_em
        ) IS DISTINCT FROM (
            NEW.carencia_pagamento_iniciada_em,
            NEW.carencia_pagamento_termina_em
        ) AND NEW.revisao <> OLD.revisao + 1 THEN
            RAISE EXCEPTION 'Alteracao da carencia financeira exige incremento unitario da revisao.' USING ERRCODE = '23514';
        END IF;

        IF (
            OLD.carencia_excesso_seats_iniciada_em,
            OLD.carencia_excesso_seats_termina_em
        ) IS DISTINCT FROM (
            NEW.carencia_excesso_seats_iniciada_em,
            NEW.carencia_excesso_seats_termina_em
        ) AND NEW.revisao <> OLD.revisao + 1 THEN
            RAISE EXCEPTION 'Alteracao da carencia de seats exige incremento unitario da revisao.' USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.status_financeiro IN (40, 50) THEN
        IF NEW.carencia_pagamento_iniciada_em IS NULL OR NEW.carencia_pagamento_termina_em IS NULL THEN
            RAISE EXCEPTION 'Status financeiro irregular exige carencia financeira completa.' USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.carencia_pagamento_iniciada_em IS NOT NULL OR NEW.carencia_pagamento_termina_em IS NOT NULL THEN
        RAISE EXCEPTION 'Status financeiro regular nao admite carencia financeira.' USING ERRCODE = '23514';
    END IF;

    IF NEW.carencia_pagamento_iniciada_em IS NOT NULL AND (
        NEW.carencia_pagamento_termina_em IS DISTINCT FROM
        NEW.carencia_pagamento_iniciada_em + NEW.carencia_pagamento_dias * INTERVAL '1 day'
    ) THEN
        RAISE EXCEPTION 'Prazo da carencia financeira diverge do snapshot contratado.' USING ERRCODE = '23514';
    END IF;

    IF (
        NEW.carencia_excesso_seats_iniciada_em IS NULL
    ) <> (
        NEW.carencia_excesso_seats_termina_em IS NULL
    ) THEN
        RAISE EXCEPTION 'Carencia de seats exige inicio e termino juntos.' USING ERRCODE = '23514';
    END IF;

    IF NEW.carencia_excesso_seats_iniciada_em IS NOT NULL AND (
        NEW.carencia_excesso_seats_termina_em IS DISTINCT FROM
        NEW.carencia_excesso_seats_iniciada_em + NEW.carencia_excesso_seats_dias * INTERVAL '1 day'
    ) THEN
        RAISE EXCEPTION 'Prazo da carencia de seats diverge do snapshot contratado.' USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER assinatura_organizacao_transicao_status
BEFORE INSERT OR UPDATE ON assinatura_organizacao
FOR EACH ROW EXECUTE FUNCTION validar_transicao_status_assinatura();
"""


RESTAURAR_TRANSICOES_ASSINATURA_POSTGRESQL = """
DROP TRIGGER IF EXISTS alteracao_assinatura_validar_fallback_trial ON alteracao_assinatura;
DROP FUNCTION IF EXISTS validar_fallback_trial_alteracao();
DROP TRIGGER IF EXISTS assinatura_organizacao_transicao_status ON assinatura_organizacao;

CREATE OR REPLACE FUNCTION validar_transicao_status_assinatura()
RETURNS trigger AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status AND NOT (
        (OLD.status = 10 AND NEW.status IN (30, 40)) OR
        (OLD.status = 20 AND NEW.status IN (30, 40)) OR
        (OLD.status = 30 AND NEW.status = 40)
    ) THEN
        RAISE EXCEPTION 'Transição inválida de status da assinatura.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER assinatura_organizacao_transicao_status
BEFORE UPDATE ON assinatura_organizacao
FOR EACH ROW EXECUTE FUNCTION validar_transicao_status_assinatura();
"""


def endurecer_transicoes_acesso(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(ENDURECER_TRANSICOES_ACESSO_POSTGRESQL)


def restaurar_transicoes_assinatura(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(RESTAURAR_TRANSICOES_ASSINATURA_POSTGRESQL)


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0010_adicionar_fallback_trial'),
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alteracaoassinatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 60), _negated=True), models.Q(('momento_aplicacao', 10), ('solicitada_por__isnull', True)), _connector='OR'), name='alteracao_fallback_trial_reservado'),
        ),
        migrations.RunPython(endurecer_transicoes_acesso, restaurar_transicoes_assinatura),
    ]
