# Generated by Django 5.2.8 on 2026-09-01 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0013_proteger_revisao_e_upserts'),
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propostacomercial',
            name='proposta_estado_datas_coerente',
        ),
        migrations.AddConstraint(
            model_name='propostacomercial',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True), ('enviada_em__isnull', True), ('status', 10), ('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True)), models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True), ('enviada_em__isnull', False), ('enviada_em__lt', models.F('valida_ate')), ('status', 20), ('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True)), models.Q(('aceita_em__isnull', False), ('aceita_em__lt', models.F('valida_ate')), ('aceita_por__isnull', False), ('enviada_em__isnull', False), ('enviada_em__lte', models.F('aceita_em')), ('status', 30), ('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True)), models.Q(('aceita_em__isnull', False), ('aceita_em__lte', models.F('ativada_em')), ('aceita_por__isnull', False), ('ativada_em__isnull', False), ('ativada_em__lt', models.F('valida_ate')), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('enviada_em__isnull', False), ('enviada_em__lte', models.F('aceita_em')), ('expirada_em__isnull', True), ('recusada_em__isnull', True), ('recusada_por__isnull', True), ('status', 40), models.Q(models.Q(('ativada_por__isnull', False), ('modo_ativacao', 20), models.Q(('justificativa_ativacao', ''), _negated=True)), models.Q(('ativada_por__isnull', True), ('justificativa_ativacao', ''), ('modo_ativacao', 10)), _connector='OR')), models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True), ('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('enviada_em__isnull', False), ('enviada_em__lte', models.F('recusada_em')), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', False), ('recusada_em__lt', models.F('valida_ate')), ('recusada_por__isnull', False), ('status', 50)), models.Q(('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', True), ('cancelada_por__isnull', True), ('enviada_em__isnull', False), ('enviada_em__lte', models.F('expirada_em')), ('expirada_em__isnull', False), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True), ('status', 60), ('valida_ate__lte', models.F('expirada_em')), models.Q(models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True)), models.Q(('aceita_em__isnull', False), ('aceita_em__lte', models.F('expirada_em')), ('aceita_por__isnull', False), ('enviada_em__lte', models.F('aceita_em'))), _connector='OR')), models.Q(('ativada_em__isnull', True), ('ativada_por__isnull', True), ('cancelada_em__isnull', False), ('cancelada_por__isnull', False), ('expirada_em__isnull', True), ('justificativa_ativacao', ''), ('recusada_em__isnull', True), ('recusada_por__isnull', True), ('status', 70), models.Q(models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True), ('enviada_em__isnull', True)), models.Q(('aceita_em__isnull', True), ('aceita_por__isnull', True), ('enviada_em__isnull', False), ('enviada_em__lte', models.F('cancelada_em'))), models.Q(('aceita_em__isnull', False), ('aceita_em__lte', models.F('cancelada_em')), ('aceita_por__isnull', False), ('enviada_em__isnull', False), ('enviada_em__lte', models.F('aceita_em'))), _connector='OR')), _connector='OR'), name='proposta_estado_datas_coerente'),
        ),
    ]
