# Generated by Django 5.2.8 on 2026-08-15 21:05

import apps.usuarios.models
import django.db.models.deletion
import django.utils.timezone
import internal_frameworks.sensitive_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('first_name', models.CharField(max_length=30, verbose_name='nome')),
                ('last_name', models.CharField(max_length=40, verbose_name='sobrenome')),
                ('email', models.EmailField(db_comment='email do usuário', help_text='email do usuário', max_length=254, verbose_name='email')),
                ('phone_number', internal_frameworks.sensitive_fields.fields.encrypt(models.CharField(blank=True, db_comment='Número de telefone E.164 cifrado.', default=None, help_text='Número de telefone E.164 cifrado.', max_length=16, null=True, verbose_name='telefone'))),
                ('phone_verified_at', models.DateTimeField(blank=True, db_comment='Data e hora da confirmação do telefone para MFA.', help_text='Data e hora da confirmação do telefone para MFA.', null=True, verbose_name='telefone verificado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'ordering': ['-id'],
                'permissions': [('can_reset_mfa_usuario', 'Pode resetar MFA de usuários')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='usuario_email_unico_nao_excluido')],
            },
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
    ]
