# Generated by Django 5.2.8 on 2026-07-30

from django.db import migrations, models


def copiar_ativo_legado_para_is_active(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    Usuario._base_manager.filter(ativo=False).update(is_active=False)


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copiar_ativo_legado_para_is_active, migrations.RunPython.noop),
        migrations.RemoveField(model_name="usuario", name="ativo"),
        migrations.AddField(
            model_name="usuario",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="excluído"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="ativo"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("email",),
                name="usuario_email_unico_nao_excluido",
            ),
        ),
    ]
