# Generated by Django 5.2.8 on 2026-07-31 15:38

import utils.sensitive_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='phone_number',
            field=utils.sensitive_fields.encrypt(models.CharField(blank=True, db_comment='Número de telefone E.164 cifrado.', default=None, help_text='Número de telefone E.164 cifrado.', max_length=16, null=True, verbose_name='telefone')),
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, db_comment='Data e hora da confirmação do telefone para MFA.', help_text='Data e hora da confirmação do telefone para MFA.', null=True, verbose_name='telefone verificado em'),
        ),
    ]
