# Generated by Django 5.2.8 on 2026-08-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado_em',
            field=models.DateTimeField(blank=True, db_comment='Data e hora da confirmação do e-mail.', help_text='Data e hora da confirmação do e-mail.', null=True, verbose_name='e-mail verificado em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='exclusao_agendada_para',
            field=models.DateTimeField(blank=True, db_comment='Data e hora programada para a anonimização definitiva da conta.', help_text='Data e hora programada para a anonimização definitiva da conta.', null=True, verbose_name='exclusão agendada para'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='exclusao_solicitada_em',
            field=models.DateTimeField(blank=True, db_comment='Data e hora em que a exclusão da conta foi solicitada.', help_text='Data e hora em que a exclusão da conta foi solicitada.', null=True, verbose_name='exclusão solicitada em'),
        ),
    ]
