# Generated by Django 5.2.8 on 2026-07-31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("usuarios", "0002_usuario_phone_number_usuario_phone_verified_at")]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "ordering": ["-id"],
                "permissions": [("can_reset_mfa_usuario", "Pode resetar MFA de usuários")],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
    ]
