# Generated by Django 5.2.8 on 2026-08-28 19:17

import apps.usuarios.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_email_verificado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'base_manager_name': 'all_objects', 'ordering': ['-id'], 'permissions': [('can_reset_mfa_usuario', 'Pode resetar MFA de usuários')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
