# Generated by Django 5.2.8 on 2026-08-28 19:58

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0003_alter_usuario_options_alter_usuario_managers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='usuario_email_unico_nao_excluido',
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('is_deleted', False)), name='usuario_email_unico_nao_excluido'),
        ),
    ]
