# Generated by Django 5.2.8 on 2026-08-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_mfa_reset_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_comment='email do usuário', help_text='email do usuário', max_length=254, verbose_name='email'),
        ),
    ]
