# Generated by Django 5.2.8 on 2026-09-22 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacoes', '0003_organizacao_email_faturamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('nome', models.CharField(db_comment='Nome do Workspace.', help_text='Nome do Workspace.', max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(db_comment='Identificador público dentro da Organização.', help_text='Identificador público dentro da Organização.', max_length=60, verbose_name='slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organizacao', models.ForeignKey(db_comment='Organização proprietária do Workspace.', help_text='Organização proprietária do Workspace.', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='organizacoes.organizacao', verbose_name='organização')),
            ],
            options={
                'db_table': 'workspace',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VinculoWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('selected_for_view', models.BooleanField(db_comment='Inclui o Workspace nas consultas automáticas.', default=True, help_text='Inclui o Workspace nas consultas automáticas.', verbose_name='selecionado para visualização')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('vinculo', models.ForeignKey(db_comment='Vínculo organizacional que recebe acesso.', help_text='Vínculo organizacional que recebe acesso.', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='organizacoes.vinculo')),
                ('workspace', models.ForeignKey(db_comment='Workspace acessível pelo vínculo.', help_text='Workspace acessível pelo vínculo.', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_vinculo',
            },
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organizacao', 'slug'), name='workspace_organizacao_slug_unico_nao_excluido'),
        ),
        migrations.AddIndex(
            model_name='vinculoworkspace',
            index=models.Index(fields=['vinculo', 'is_active', 'selected_for_view'], name='wv_vinculo_ativo_sel_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculoworkspace',
            index=models.Index(fields=['workspace', 'is_active'], name='wv_workspace_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='vinculoworkspace',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('vinculo', 'workspace'), name='workspace_vinculo_unico_nao_excluido'),
        ),
    ]
