# Generated by Django 5.2.8 on 2026-08-15 21:05

import django.db.models.deletion
import internal_frameworks.sensitive_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('digest', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='digest')),
                ('token_key', models.CharField(db_index=True, max_length=25, verbose_name='chave do token')),
                ('expiry', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Token'), (2, 'Reset de senha'), (3, 'Pré-autenticação'), (999, 'API key')], db_index=True, default=1, verbose_name='tipo')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='nome')),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Escopos `resource:action` concedidos a uma API key.', verbose_name='escopos')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='suspenso em')),
                ('suspension_reason', models.CharField(blank=True, max_length=255, verbose_name='motivo da suspensão')),
            ],
            options={
                'verbose_name': 'Token de autenticação',
                'verbose_name_plural': 'Tokens de autenticação',
                'db_table': 'auth_token',
                'ordering': ('-created_at',),
                'permissions': [('view_apikey', 'Pode ver API keys'), ('add_apikey', 'Pode criar API keys'), ('change_apikey', 'Pode alterar API keys'), ('delete_apikey', 'Pode revogar API keys'), ('rotate_apikey', 'Pode rotacionar API keys')],
                'swappable': 'KNOX_TOKEN_MODEL',
            },
        ),
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('enrollment', 'Cadastro de fator'), ('reauthentication', 'Reautenticação')], max_length=24, verbose_name='finalidade')),
                ('otp_digest', models.CharField(blank=True, max_length=128, verbose_name='digest do OTP')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expira em')),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='cooldown até')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=16, verbose_name='estado de entrega')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'db_table': 'mfa_challenge',
            },
        ),
        migrations.CreateModel(
            name='MFAFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('totp', 'TOTP')], max_length=16, verbose_name='tipo')),
                ('secret', internal_frameworks.sensitive_fields.fields.encrypt(models.CharField(blank=True, db_comment='Segredo TOTP cifrado.', default=None, help_text='Segredo TOTP cifrado.', max_length=64, null=True, verbose_name='segredo'))),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='ativado em')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='desativado em')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado por último em')),
                ('totp_last_counter', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='último contador TOTP')),
                ('totp_algorithm', models.CharField(default='SHA1', max_length=16, verbose_name='algoritmo TOTP')),
                ('totp_digits', models.PositiveSmallIntegerField(default=6, verbose_name='dígitos TOTP')),
                ('totp_period', models.PositiveSmallIntegerField(default=30, verbose_name='período TOTP')),
            ],
            options={
                'db_table': 'mfa_factor',
            },
        ),
        migrations.CreateModel(
            name='MFARecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=128, verbose_name='digest')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumido em')),
            ],
            options={
                'db_table': 'mfa_recovery_code',
            },
        ),
        migrations.CreateModel(
            name='MFAResetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mfa_reset_audit',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=128, unique=True, verbose_name='digest')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='nome')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expira em')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado por último em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
            ],
            options={
                'db_table': 'trusted_device',
            },
        ),
        migrations.CreateModel(
            name='TokenMetaData',
            fields=[
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to=settings.KNOX_TOKEN_MODEL, verbose_name='Token')),
                ('device_name', models.CharField(blank=True, help_text="Nome personalizado do dispositivo (ex: 'iPhone de Rafael')", max_length=255, verbose_name='Nome do dispositivo')),
                ('device_type', models.CharField(choices=[('mobile', 'Celular'), ('tablet', 'Tablet'), ('desktop', 'Computador'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Tipo de dispositivo')),
                ('device_brand', models.CharField(blank=True, help_text='Marca do dispositivo (ex: Apple, Samsung, etc)', max_length=100, verbose_name='Marca do dispositivo')),
                ('device_model', models.CharField(blank=True, help_text='Modelo do dispositivo (ex: iPhone 14 Pro, Galaxy S23)', max_length=100, verbose_name='Modelo do dispositivo')),
                ('os_name', models.CharField(blank=True, help_text='Nome do SO (iOS, Android, Windows, macOS, Linux)', max_length=50, verbose_name='Nome do sistema operacional')),
                ('os_version', models.CharField(blank=True, help_text='Versão do SO', max_length=50, verbose_name='Versão do sistema operacional')),
                ('browser_name', models.CharField(blank=True, help_text='Nome do navegador ou app', max_length=50, verbose_name='Nome do navegador')),
                ('browser_version', models.CharField(blank=True, max_length=50, verbose_name='Versão do navegador')),
                ('user_agent', models.TextField(blank=True, help_text='User agent completo da requisição', verbose_name='User agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP da origem', null=True, verbose_name='Endereço IP')),
                ('country', models.CharField(blank=True, help_text='País', max_length=100, verbose_name='País')),
                ('country_code', models.CharField(blank=True, help_text='Código do país (ISO 3166-1 alpha-2)', max_length=2, verbose_name='Código do país')),
                ('region', models.CharField(blank=True, help_text='Estado/Região', max_length=100, verbose_name='Estado/Região')),
                ('city', models.CharField(blank=True, help_text='Cidade', max_length=100, verbose_name='Cidade')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('timezone', models.CharField(blank=True, help_text='Fuso horário (ex: America/Sao_Paulo)', max_length=50, verbose_name='Fuso horário')),
                ('isp', models.CharField(blank=True, help_text='Provedor de internet', max_length=255, verbose_name='Provedor de internet')),
                ('first_used', models.DateTimeField(auto_now_add=True, help_text='Primeira vez que o token foi usado', verbose_name='Primeiro uso')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Última vez que o token foi usado', verbose_name='Último uso')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Número de vezes que o token foi usado', verbose_name='Contador de uso')),
                ('reauthenticated_at', models.DateTimeField(blank=True, db_comment='Data e hora da última confirmação recente de senha da sessão.', help_text='Data e hora da última confirmação recente de senha da sessão.', null=True, verbose_name='Reautenticado em')),
                ('is_suspicious', models.BooleanField(default=False, help_text='Marcado como suspeito por mudança de IP/localização', verbose_name='É suspeito')),
                ('suspicious_reason', models.TextField(blank=True, help_text='Motivo da suspeita', verbose_name='Motivo da suspeita')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='Score de risco (0-100)', verbose_name='Pontuação de risco')),
                ('app_version', models.CharField(blank=True, help_text='Versão do app/frontend (ex: 1.2.3)', max_length=20, verbose_name='Versão do app')),
                ('fcm_token', models.TextField(blank=True, help_text='Token para push notifications (Firebase Cloud Messaging)', verbose_name='Token FCM')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Dados adicionais em formato JSON', verbose_name='Dados extras')),
            ],
            options={
                'verbose_name': 'Metadado de token',
                'verbose_name_plural': 'Metadados de tokens',
                'db_table': 'token_metadata',
                'ordering': ['-last_used'],
                'permissions': [('grant_unrestricted_apikey', 'Pode conceder API keys com scope irrestrito (*)')],
            },
        ),
    ]
