# Generated by Django 5.2.8 on 2026-07-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "digest",
                    models.CharField(
                        db_comment="Hash criptográfico irreversível do segredo do token.",
                        help_text="Hash criptográfico irreversível do segredo do token.",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Digest",
                    ),
                ),
                (
                    "token_key",
                    models.CharField(
                        db_comment="Prefixo não sensível do token usado para identificação rápida.",
                        db_index=True,
                        help_text="Prefixo não sensível do token usado para identificação rápida.",
                        max_length=25,
                        verbose_name="Prefixo do token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Data e hora de emissão do token.",
                        help_text="Data e hora de emissão do token.",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "expiry",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Data e hora de expiração do token, obrigatória para tipos efêmeros.",
                        help_text="Data e hora de expiração do token, obrigatória para tipos efêmeros.",
                        null=True,
                        verbose_name="Expira em",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Token"), (2, "Reset de senha"), (3, "Pré-autenticação"), (999, "API key")],
                        db_comment="Tipo operacional do token.",
                        db_index=True,
                        default=1,
                        help_text="Tipo operacional do token.",
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        db_comment="Escopos autorizados para o token, aplicáveis a API keys.",
                        default=list,
                        help_text="Escopos autorizados para o token, aplicáveis a API keys.",
                        verbose_name="Escopos",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        db_comment="Usuário responsável pelo token.",
                        help_text="Usuário responsável pelo token.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "db_table": "auth_token",
                "ordering": ("-created_at",),
                "swappable": "KNOX_TOKEN_MODEL",
                "verbose_name": "Token de autenticação",
                "verbose_name_plural": "Tokens de autenticação",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("type__in", (3, 2)), _negated=True) | models.Q(("expiry__isnull", False)),
                        name="auth_token_ephemeral_requires_expiry",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TokenMetaData",
            fields=[
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="metadata",
                        serialize=False,
                        to="autenticacao.authtoken",
                        verbose_name="Token",
                    ),
                ),
                ("device_name", models.CharField(blank=True, help_text="Nome personalizado do dispositivo (ex: 'iPhone de Rafael')", max_length=255, verbose_name="Nome do dispositivo")),
                ("device_type", models.CharField(choices=[("mobile", "Celular"), ("tablet", "Tablet"), ("desktop", "Computador"), ("unknown", "Desconhecido")], default="unknown", max_length=20, verbose_name="Tipo de dispositivo")),
                ("device_brand", models.CharField(blank=True, help_text="Marca do dispositivo (ex: Apple, Samsung, etc)", max_length=100, verbose_name="Marca do dispositivo")),
                ("device_model", models.CharField(blank=True, help_text="Modelo do dispositivo (ex: iPhone 14 Pro, Galaxy S23)", max_length=100, verbose_name="Modelo do dispositivo")),
                ("os_name", models.CharField(blank=True, help_text="Nome do SO (iOS, Android, Windows, macOS, Linux)", max_length=50, verbose_name="Nome do sistema operacional")),
                ("os_version", models.CharField(blank=True, help_text="Versão do SO", max_length=50, verbose_name="Versão do sistema operacional")),
                ("browser_name", models.CharField(blank=True, help_text="Nome do navegador ou app", max_length=50, verbose_name="Nome do navegador")),
                ("browser_version", models.CharField(blank=True, max_length=50, verbose_name="Versão do navegador")),
                ("user_agent", models.TextField(blank=True, help_text="User agent completo da requisição", verbose_name="User agent")),
                ("ip_address", models.GenericIPAddressField(blank=True, help_text="Endereço IP da origem", null=True, verbose_name="Endereço IP")),
                ("country", models.CharField(blank=True, help_text="País", max_length=100, verbose_name="País")),
                ("country_code", models.CharField(blank=True, help_text="Código do país (ISO 3166-1 alpha-2)", max_length=2, verbose_name="Código do país")),
                ("region", models.CharField(blank=True, help_text="Estado/Região", max_length=100, verbose_name="Estado/Região")),
                ("city", models.CharField(blank=True, help_text="Cidade", max_length=100, verbose_name="Cidade")),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Latitude")),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Longitude")),
                ("timezone", models.CharField(blank=True, help_text="Fuso horário (ex: America/Sao_Paulo)", max_length=50, verbose_name="Fuso horário")),
                ("isp", models.CharField(blank=True, help_text="Provedor de internet", max_length=255, verbose_name="Provedor de internet")),
                ("first_used", models.DateTimeField(auto_now_add=True, help_text="Primeira vez que o token foi usado", verbose_name="Primeiro uso")),
                ("last_used", models.DateTimeField(auto_now=True, help_text="Última vez que o token foi usado", verbose_name="Último uso")),
                ("usage_count", models.PositiveIntegerField(default=0, help_text="Número de vezes que o token foi usado", verbose_name="Contador de uso")),
                ("is_suspicious", models.BooleanField(default=False, help_text="Marcado como suspeito por mudança de IP/localização", verbose_name="É suspeito")),
                ("suspicious_reason", models.TextField(blank=True, help_text="Motivo da suspeita", verbose_name="Motivo da suspeita")),
                ("risk_score", models.PositiveSmallIntegerField(default=0, help_text="Score de risco (0-100)", verbose_name="Pontuação de risco")),
                ("app_version", models.CharField(blank=True, help_text="Versão do app/frontend (ex: 1.2.3)", max_length=20, verbose_name="Versão do app")),
                ("fcm_token", models.TextField(blank=True, help_text="Token para push notifications (Firebase Cloud Messaging)", verbose_name="Token FCM")),
                ("extra_data", models.JSONField(blank=True, default=dict, help_text="Dados adicionais em formato JSON", verbose_name="Dados extras")),
            ],
            options={
                "verbose_name": "Metadado de token",
                "verbose_name_plural": "Metadados de tokens",
                "db_table": "token_metadata",
                "ordering": ["-last_used"],
            },
        ),
    ]
