# Generated by Django 5.2.8 on 2026-08-15 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='organizacoes.organizacao', verbose_name='organização'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to=settings.KNOX_TOKEN_MODEL, verbose_name='substituído por'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token_set', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='revogado por'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='suspenso por'),
        ),
        migrations.AddField(
            model_name='mfachallenge',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.KNOX_TOKEN_MODEL, verbose_name='token de autenticação'),
        ),
        migrations.AddField(
            model_name='mfachallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='mfafactor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_factors', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='mfachallenge',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='autenticacao.mfafactor', verbose_name='fator'),
        ),
        migrations.AddField(
            model_name='mfarecoverycode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_recovery_codes', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='mfaresetaudit',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mfa_resets_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mfaresetaudit',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_resets_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddConstraint(
            model_name='authtoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 999), ('organization__isnull', False)), models.Q(models.Q(('type', 999), _negated=True), ('organization__isnull', True)), _connector='OR'), name='auth_token_api_key_exige_organizacao'),
        ),
        migrations.AddConstraint(
            model_name='authtoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 999), _negated=True), models.Q(('created_by__isnull', False), models.Q(('name', ''), _negated=True)), _connector='OR'), name='auth_token_api_key_exige_nome_e_criador'),
        ),
        migrations.AddConstraint(
            model_name='authtoken',
            constraint=models.CheckConstraint(condition=models.Q(('type', 999), models.Q(('name', ''), ('scopes', [])), _connector='OR'), name='auth_token_sessao_sem_campos_de_api_key'),
        ),
        migrations.AddConstraint(
            model_name='mfafactor',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='mfa_factor_unique_user_type'),
        ),
        migrations.AddConstraint(
            model_name='mfafactor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'totp'), ('secret__isnull', False)), models.Q(models.Q(('type', 'totp'), _negated=True), ('secret__isnull', True)), _connector='OR'), name='mfa_factor_totp_secret_only'),
        ),
        migrations.AddIndex(
            model_name='mfachallenge',
            index=models.Index(fields=['user', 'expires_at'], name='mfa_challenge_user_expiry'),
        ),
        migrations.AddConstraint(
            model_name='mfarecoverycode',
            constraint=models.CheckConstraint(condition=models.Q(('digest', ''), _negated=True), name='mfa_recovery_code_requires_digest'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'expires_at'], name='trusted_device_user_expiry'),
        ),
        migrations.AddConstraint(
            model_name='trusteddevice',
            constraint=models.CheckConstraint(condition=models.Q(('digest', ''), _negated=True), name='trusted_device_requires_digest'),
        ),
    ]
