# Generated by Django 5.2.8 on 2026-07-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenmetadata',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Token'), (2, 'Reset de senha'), (999, 'API key')], db_index=True, default=1, help_text='Tipo de uso do token Knox.', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='tokenmetadata',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text="Escopos concedidos ao token API key, como 'org:read'.", verbose_name='Escopos'),
        ),
    ]
