# Generated by Django 5.2.8 on 2026-08-28 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadeExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='última alteração em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('provedor', models.PositiveSmallIntegerField(choices=[(10, 'Google')], db_comment='Provedor que emitiu o identificador externo.', help_text='Provedor que emitiu o identificador externo.', verbose_name='provedor')),
                ('identificador', models.CharField(db_comment='Identificador imutável fornecido pelo provedor externo.', help_text='Identificador imutável fornecido pelo provedor externo.', max_length=255, verbose_name='identificador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('usuario', models.ForeignKey(db_comment='Usuário dono da identidade externa.', help_text='Usuário dono da identidade externa.', on_delete=django.db.models.deletion.CASCADE, related_name='identidades_externas', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Identidade externa',
                'verbose_name_plural': 'Identidades externas',
                'db_table': 'identidade_externa',
                'ordering': ('-id',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('provedor', 'identificador'), name='identidade_externa_provedor_identificador_unico_nao_excluido'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('usuario', 'provedor'), name='identidade_externa_usuario_provedor_unico_nao_excluido')],
            },
        ),
    ]
