# Generated by Django 5.2.8 on 2026-07-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autenticacao", "0003_reconcile_custom_token_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(model_name="authtoken", name="created_at", field=models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
        migrations.AlterField(model_name="authtoken", name="digest", field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name="digest")),
        migrations.AlterField(model_name="authtoken", name="expiry", field=models.DateTimeField(blank=True, null=True, verbose_name="expira em")),
        migrations.AlterField(model_name="authtoken", name="responsavel", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="auth_token_set", to=settings.AUTH_USER_MODEL, verbose_name="responsável")),
        migrations.AlterField(model_name="authtoken", name="scopes", field=models.JSONField(blank=True, default=list, help_text="Escopos `resource:action` concedidos a uma API key.", verbose_name="escopos")),
        migrations.AlterField(model_name="authtoken", name="token_key", field=models.CharField(db_index=True, max_length=25, verbose_name="chave do token")),
        migrations.AlterField(model_name="authtoken", name="type", field=models.PositiveSmallIntegerField(choices=[(1, "Token"), (2, "Reset de senha"), (999, "API key")], db_index=True, default=1, verbose_name="tipo")),
    ]
