# Generated by Django 5.2.8 on 2026-08-28 19:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_identidadeexterna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identidadeexterna',
            options={'base_manager_name': 'all_objects', 'ordering': ('-id',), 'verbose_name': 'Identidade externa', 'verbose_name_plural': 'Identidades externas'},
        ),
        migrations.AlterModelManagers(
            name='identidadeexterna',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
