# Generated by Django 5.2.8 on 2026-09-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_identidadeexterna_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenmetadata',
            options={'ordering': ['-last_used'], 'permissions': [('grant_api_scopes', 'Pode conceder scopes disponíveis para API keys'), ('grant_unrestricted_apikey', 'Pode conceder API keys com scope irrestrito (*)')], 'verbose_name': 'Metadado de token', 'verbose_name_plural': 'Metadados de tokens'},
        ),
    ]
