# Generated by Django 5.2.8 on 2026-07-31 15:38

import django.db.models.deletion
import internal_frameworks.sensitive_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_authtoken_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('totp', 'TOTP')], max_length=16, verbose_name='tipo')),
                ('secret', internal_frameworks.sensitive_fields.fields.encrypt(models.CharField(blank=True, db_comment='Segredo TOTP cifrado.', default=None, help_text='Segredo TOTP cifrado.', max_length=64, null=True, verbose_name='segredo'))),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='ativado em')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='desativado em')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado por último em')),
                ('totp_last_counter', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='último contador TOTP')),
                ('totp_algorithm', models.CharField(default='SHA1', max_length=16, verbose_name='algoritmo TOTP')),
                ('totp_digits', models.PositiveSmallIntegerField(default=6, verbose_name='dígitos TOTP')),
                ('totp_period', models.PositiveSmallIntegerField(default=30, verbose_name='período TOTP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_factors', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'db_table': 'mfa_factor',
            },
        ),
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('enrollment', 'Cadastro de fator'), ('reauthentication', 'Reautenticação')], max_length=24, verbose_name='finalidade')),
                ('otp_digest', models.CharField(blank=True, max_length=128, verbose_name='digest do OTP')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expira em')),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='cooldown até')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=16, verbose_name='estado de entrega')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to='autenticacao.authtoken', verbose_name='token de autenticação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='autenticacao.mfafactor', verbose_name='fator')),
            ],
            options={
                'db_table': 'mfa_challenge',
            },
        ),
        migrations.CreateModel(
            name='MFARecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=128, verbose_name='digest')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumido em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_recovery_codes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'db_table': 'mfa_recovery_code',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=128, unique=True, verbose_name='digest')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='nome')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expira em')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado por último em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'db_table': 'trusted_device',
            },
        ),
        migrations.AddConstraint(
            model_name='mfafactor',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='mfa_factor_unique_user_type'),
        ),
        migrations.AddConstraint(
            model_name='mfafactor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'totp'), ('secret__isnull', False)), models.Q(models.Q(('type', 'totp'), _negated=True), ('secret__isnull', True)), _connector='OR'), name='mfa_factor_totp_secret_only'),
        ),
        migrations.AddIndex(
            model_name='mfachallenge',
            index=models.Index(fields=['user', 'expires_at'], name='mfa_challenge_user_expiry'),
        ),
        migrations.AddConstraint(
            model_name='mfarecoverycode',
            constraint=models.CheckConstraint(condition=models.Q(('digest', ''), _negated=True), name='mfa_recovery_code_requires_digest'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'expires_at'], name='trusted_device_user_expiry'),
        ),
        migrations.AddConstraint(
            model_name='trusteddevice',
            constraint=models.CheckConstraint(condition=models.Q(('digest', ''), _negated=True), name='trusted_device_requires_digest'),
        ),
    ]
