# Generated by Django 5.2.8 on 2026-08-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autenticacao", "0008_mfa_reset_audit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authtoken",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Token"), (2, "Reset de senha"), (3, "Pré-autenticação"), (999, "API key")],
                db_index=True,
                default=1,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="tokenmetadata",
            name="reauthenticated_at",
            field=models.DateTimeField(
                blank=True,
                db_comment="Data e hora da última confirmação recente de senha da sessão.",
                help_text="Data e hora da última confirmação recente de senha da sessão.",
                null=True,
                verbose_name="Reautenticado em",
            ),
        ),
    ]
